### ISSUE TITLE
markdown中<h字符导致文章不能查看问题

### ISSUE THREAD

**Issue by eelve** [xzhuz/halo-theme-xue#100]
markdown中，包含 <h 字符串是，导致文章不能正常查看
![图片](https://user-images.githubusercontent.com/13844973/98446519-ec495680-2158-11eb-9097-9c3c558ec2b5.png)
预览或者发布是，文章都不能正常渲染
![图片](https://user-images.githubusercontent.com/13844973/98446524-f2d7ce00-2158-11eb-92bd-a1ab1ab30b82.png)

经过排查，排除halo的问题，测试发现为主题导致

**Comment by xzhuz** [comment]
下个版本的时候修复掉

**Comment by xzhuz** [comment]
请关注[1.2.3](https://github.com/xzhuz/halo-theme-xue/releases/tag/1.23.3)版本
