### ISSUE TITLE
启用相册后，相册懒加载问题

### ISSUE THREAD

**Issue by Dovesly** [xzhuz/halo-theme-xue#101]
您好，我个人偏向于放一些照片上去，所以在启用相册的时候回一次性加载后台所有照片出来，如果后台图片过多，会导致图片加载很久加载不出来。

**Comment by xzhuz** [comment]
请问是使用的什么版本？

**Comment by Dovesly** [comment]
halo-theme-xue_hotfix_2.zip 用的这个 大概就是这个情况
![image](https://user-images.githubusercontent.com/42823831/98463219-ac37b180-21f4-11eb-9a87-66d47bbb1480.png)

**Comment by xzhuz** [comment]
你的发过来看下呢？

**Comment by Dovesly** [comment]
https://visionsly.cn/ 那个Photography

**Comment by xzhuz** [comment]
请关注 https://github.com/xzhuz/halo-theme-xue/releases/tag/1.2.3.beta.6

**Comment by xzhuz** [comment]
请关注[1.2.3](https://github.com/xzhuz/halo-theme-xue/releases/tag/1.2.3)版本
