### ISSUE TITLE
上一篇 的图片总是undefined

### ISSUE THREAD

**Issue by ssymon** [xzhuz/halo-theme-xue#102]
![image](https://user-images.githubusercontent.com/37892706/98556025-9225ce00-22dd-11eb-9930-34a29d52e986.png)
![image](https://user-images.githubusercontent.com/37892706/98556418-fb0d4600-22dd-11eb-9dcd-a2b1f8390898.png)
这是啥问题呀 更了最新的代码

**Comment by zhixiangyuan** [comment]
我这边出现了类似的问题，看上去感觉是碰到了空行

第一章图是我后台的配置，有空行，第二张图是图片渲染出来的效果，第三张图是 html 代码，里面是空的，所以感觉是没有过滤空行的问题。

![image](https://user-images.githubusercontent.com/25138766/98618160-8a951200-233b-11eb-88a1-f63f39d8026c.png)

![image](https://user-images.githubusercontent.com/25138766/98618234-aef0ee80-233b-11eb-8593-8e3e9a4ccda9.png)

![image](https://user-images.githubusercontent.com/25138766/98618185-97b20100-233b-11eb-81fb-3880432538e6.png)

**Comment by xzhuz** [comment]
额，这个是个问题，最新代码修复了。只是么有发布版本

**Comment by zhixiangyuan** [comment]
> 额，这个是个问题，最新代码修复了。只是么有发布版本

大佬啥时候发个 1.2.3 的版本

**Comment by ssymon** [comment]
> 额，这个是个问题，最新代码修复了。只是么有发布版本

期待 最新版的 发布

**Comment by xzhuz** [comment]
我看目前是好的

**Comment by xzhuz** [comment]
请关注 https://github.com/xzhuz/halo-theme-xue/releases/tag/1.2.3.beta.6

**Comment by ruibaby** [comment]
> 1.2.3.beta.6

此版本同样有这样的问题。

**Comment by xzhuz** [comment]
> > 1.2.3.beta.6
> 
> 此版本同样有这样的问题。
那就在1.2.3中修复

**Comment by xzhuz** [comment]
请关注[1.2.3](https://github.com/xzhuz/halo-theme-xue/releases/tag/1.2.3)版本
