### ISSUE TITLE
bug: 数学公式不居中

### ISSUE THREAD

**Issue by zhixiangyuan** [xzhuz/halo-theme-xue#104]
## 期望行为

数学公式居中

## 当前行为

数学公式使用 `$$xxx$$` 时不居中

![image](https://user-images.githubusercontent.com/25138766/99020637-f96fa680-2599-11eb-9223-44ec6f9778d8.png)

**Comment by xzhuz** [comment]
表现为可以显示正常的公式，只是不居中吗？

**Comment by zhixiangyuan** [comment]
> 表现为可以显示正常的公式，只是不居中吗？

是的

**Comment by xzhuz** [comment]
请关注 https://github.com/xzhuz/halo-theme-xue/releases/tag/1.2.3.beta.6

**Comment by xzhuz** [comment]
请关注[1.2.3](https://github.com/xzhuz/halo-theme-xue/releases/tag/1.2.3)版本
