### ISSUE TITLE
点击首页左上侧菜单图标后，鼠标移到菜单上文字消失的问题

### ISSUE THREAD

**Issue by bufflu** [xzhuz/halo-theme-xue#108]
正常点击：
![图片](https://user-images.githubusercontent.com/33686316/100838345-38b05980-34ad-11eb-8b7b-674db0769b41.png)
![图片](https://user-images.githubusercontent.com/33686316/100838380-449c1b80-34ad-11eb-973c-ab795cf06760.png)
很大概率出现菜单消失情况：
![图片](https://user-images.githubusercontent.com/33686316/100838392-4c5bc000-34ad-11eb-94e5-63485dfd709a.png)

**Comment by xzhuz** [comment]
是移到菜单上就消失了吗？

**Comment by bufflu** [comment]
不是，是点击图标之后，鼠标往右下方向滑动时候会导致菜单消失（类似倒着画一个三角形），对前端不是很懂，如果需要我可以录一段视频

**Comment by bufflu** [comment]
点击完之后鼠标移动的稍微快些，应该会复现

**Comment by xzhuz** [comment]
> 不是，是点击图标之后，鼠标往右下方向滑动时候会导致菜单消失（类似倒着画一个三角形），对前端不是很懂，如果需要我可以录一段视频

可以弄一个gif

**Comment by bufflu** [comment]
> > 不是，是点击图标之后，鼠标往右下方向滑动时候会导致菜单消失（类似倒着画一个三角形），对前端不是很懂，如果需要我可以录一段视频
> 
> 可以弄一个gif

**Comment by bufflu** [comment]
![图片](https://user-images.githubusercontent.com/33686316/100953706-0e62a880-354e-11eb-87e2-940b609b5be5.png)

**Comment by bufflu** [comment]
我给您发邮箱了

> > 不是，是点击图标之后，鼠标往右下方向滑动时候会导致菜单消失（类似倒着画一个三角形），对前端不是很懂，如果需要我可以录一段视频
> 
> 可以弄一个gif

我给您发到邮箱里了，请查收。

**Comment by xzhuz** [comment]
> 我给您发邮箱了
> 
> > > 不是，是点击图标之后，鼠标往右下方向滑动时候会导致菜单消失（类似倒着画一个三角形），对前端不是很懂，如果需要我可以录一段视频
> > 
> > 
> > 可以弄一个gif
> 
> 我给您发到邮箱里了，请查收。
并没有收到相关邮件

**Comment by xzhuz** [comment]
可以看下你的网站吗

**Comment by bufflu** [comment]
> 
> 
> 可以看下你的网站吗

http://www.wo66.cc
示例的主页也有相同的问题

**Comment by xzhuz** [comment]
你是用的什么浏览器呢？你的网站是我这边尝试了是好的。

**Comment by bufflu** [comment]
> 你是用的什么浏览器呢？

Firefox

**Comment by xzhuz** [comment]
> > 你是用的什么浏览器呢？
> 
> Firefox

你用其他浏览器试过吗，也是这样子吗

**Comment by xzhuz** [comment]
你加我微信吧，私聊一下

**Comment by bufflu** [comment]
> 你加我微信吧，私聊一下

试了一下 Safari 没有这个问题，您微信是 「飞翔的竹蜻蜓」 吗？

**Comment by xzhuz** [comment]
注意readme有贴微信二维码
