### ISSUE TITLE
首页文章列表的封面问题

### ISSUE THREAD

**Issue by thomas10011** [xzhuz/halo-theme-xue#110]
当且版本中，首页文章列表展示风格是列表模式时，文章的缩略封面图默认是日期，鼠标放上去才会显示文章的封面图片缩略图。
希望能增加一个功能，让用户选择文章列表默认展示封面缩略图，鼠标放上去之后显示日期。

**Comment by xzhuz** [comment]
请关注[1.2.3](https://github.com/xzhuz/halo-theme-xue/releases/tag/1.23.3)版本
