### ISSUE TITLE
代码块可以加个折叠功能吗？

### ISSUE THREAD

**Issue by MakiseVon** [xzhuz/halo-theme-xue#111]
如题 ~

**Comment by xzhuz** [comment]
目前还没有找到技术方案，也不知道目前的halo主题有没有支持这个功能。如果你有好的方案可以提出来，后续我也会持续关注

**Comment by MakiseVon** [comment]
我有尝试过，参考了 cnblogs 的实现，用的是 `<details><summary></summary></details>` 标签。
想法是开启该功能后找到所有符合条件的代码块，形如

````
```cpp summary
code
```
````

替换为

````
<details>
<summary>summary</summary>

```cpp
code
```

</details>
````

基础效果如下：

<details>
<summary>summary</summary>

```cpp
code
```

</details>

在这个基础上再修改样式。
因为对 js 的正则匹配不熟悉所以最后没弄出来 orz

**Comment by xzhuz** [comment]
看起来好像不是很复杂的样子，如果可以的话，我在下个版本中加上。

**Comment by xzhuz** [comment]
请关注[1.2.3](https://github.com/xzhuz/halo-theme-xue/releases/tag/1.2.3)版本
