### ISSUE TITLE
1.2.3 随机封面图失效 & 上一篇、下一篇文章图片懒加载失效

### ISSUE THREAD

**Issue by MakiseVon** [xzhuz/halo-theme-xue#113]
已设置随机封面图
首页中效果如下

![1.png](https://i.loli.net/2020/12/19/TZaj2zFD731qG5o.png)

文章如果单独设置了封面图，在上一篇、下一篇中效果如下

![2.png](https://i.loli.net/2020/12/19/ZBLSUriD8qTQP1A.png)

Failed to load resource: the server responded with a status of 404 ()
siteurl/archives/undefined
siteurl/undefined

**Comment by xzhuz** [comment]
1.2.3 版本的 halo-theme-xue.zip 最新版修复了 此bug
