### ISSUE TITLE
开启全局 Pjax 后从首页进入文章页不显示文章目录

### ISSUE THREAD

**Issue by MakiseVon** [xzhuz/halo-theme-xue#115]
1. 开启全站Pjax
2. 从首页进入文章页，不显示目录
3. 强制刷新文章页，显示目录
4. 回到主页再次进入文章页，不显示目录且报如下错误

```
tocbot.min.js:1 Uncaught TypeError: Cannot read property 'className' of null
    at Object.updateToc (tocbot.min.js:1)
    at HTMLDocument.<anonymous> (tocbot.min.js:1)
    at HTMLDocument.<anonymous> (tocbot.min.js:1)
```

好像从上个版本就有了，但当时我以为是我自己不小心修改了什么地方。
升级到1.2.3后依然留有，我看了其他开启了 Pjax 的示例站点，貌似是没有这个问题的。

对比以下两个博客
[Makise Von's Blog](https://makisevon.net/)
[Symon's Blog](https://www.ssymon.com/)

**Comment by xzhuz** [comment]
目前此问题已修复。你查看最新1.2.3版本的 bugfix
