### ISSUE TITLE
翻页http://{域名}/page/1随机图片失效，首页http://{域名}显示正常

### ISSUE THREAD

**Issue by coderqianlq** [xzhuz/halo-theme-xue#117]
如题

**Comment by xzhuz** [comment]
开启了pjax了吗？

**Comment by coderqianlq** [comment]
> 开启了pjax了吗？

开启和关闭都不行

**Comment by xzhuz** [comment]
你的主题用的什么版本的？是否下载了目前1.2.3版本中最新的halo-theme-xue.zip？

**Comment by xzhuz** [comment]
https://github.com/xzhuz/halo-theme-xue/releases/tag/1.2.3 
请重新下载这个版本下的zip，并安装
