### ISSUE TITLE
随机图片功能增强

### ISSUE THREAD

**Issue by zhixiangyuan** [xzhuz/halo-theme-xue#119]
建议网页首部图片里面可以设置为空，如果设置为空则从随机图片里面选择一张。想添加这个功能的原因是每天看同一张图片看久了有点腻。

![image](https://user-images.githubusercontent.com/25138766/103172022-6c538900-488b-11eb-8f3d-4e29fdad09f8.png)

**Comment by xzhuz** [comment]
倒是可以做，但是感觉这样会增加复杂度，没有必要。因为按照你的需求，你可以随时修改，这个首页图片
