### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by waltz26** [xzhuz/halo-theme-xue#122]
使用该主题挺久了，集合一下遇到的一些问题和觉得可以改进的点：
1.数学公式换行没有渲染到，例如此文章中矩阵元素全集合在一行：[问题文章](https://www.waltz26.cn/archives/s1-%E7%9F%A9%E9%98%B5%E5%BF%AB%E9%80%9F%E5%B9%82%E4%B8%8E%E7%9F%A9%E9%98%B5%E5%8A%A0%E9%80%9F)
2.代码块折叠时，下方的< hr> 会紧紧贴在下面，导致看不见< hr> ：[问题文章](https://www.waltz26.cn/archives/p2-%E5%B9%BF%E5%B7%9E%E5%A4%A7%E5%AD%A6acm%E6%9A%91%E5%81%87%E9%9B%86%E8%AE%ADday1-7-20%E9%A2%98%E8%A7%A3#SfPBxmCM)
另外觉得
3.希望可以添加设置设定超链接的颜色，灰色实在是不太明显，希望能像是“寒山志”那样的
4.评论显示不了自己的答复

**Comment by xzhuz** [comment]
回复：
1、你是想每个公示都换行吗？
2、这个不是一个<hr> 
3、确实没有寒山志的好看
4、你是使用的自己的邮箱和网站回复的吗？

**Comment by waltz26** [comment]
追加：
1.例如此文章第一个数字公式想要显示的是一个矩阵，可是并没有正确显示出来，而是集中在一行上，后面还有一个矩阵计算的公式超出了文章内容width范围
2.大佬可以检查一下最后一个折叠代码块处的内容，紧接代码块底下有一个< hr >标签
4.我是在后台回复的

抱歉本人描述能力不太足

**Comment by xzhuz** [comment]
> 追加：
> 1.例如此文章第一个数字公式想要显示的是一个矩阵，可是并没有正确显示出来，而是集中在一行上，后面还有一个矩阵计算的公式超出了文章内容width范围
> 2.大佬可以检查一下最后一个折叠代码块处的内容，紧接代码块底下有一个< hr >标签
> 4.我是在后台回复的
> 
> 抱歉本人描述能力不太足

1、是css的样式问题，后面看看，你可以公式源代码贴出来。
2、我就是看的最后一个，我看到的不是hr，是因为 border + margin 的原因
3、这个你可以去halo 仓库问问。后台的话，我也是没有办法的

**Comment by waltz26** [comment]
公式源码
```
$$
\begin{bmatrix}
2&3&4\\
1&6&5
\end{bmatrix}
\begin{bmatrix}
3&1&3\\
3&2&3\\
3&1&3
\end{bmatrix}
\begin{bmatrix}
1&0&0&0\\
0&1&0&0\\
0&0&1&0\\
0&0&0&1
\end{bmatrix}
$$
```

**Comment by xzhuz** [comment]
[halo-theme-xue.katex.zip](https://github.com/xzhuz/halo-theme-xue/files/5793599/halo-theme-xue.katex.zip)
你可以 使用这个主题包，基本能解决这些公式的问题
