### ISSUE TITLE
我现在想修改你的主题，想在iconfont里面添加几个新的图标，这个怎么操作呢

### ISSUE THREAD

**Issue by mytianya** [xzhuz/halo-theme-xue#124]

**Comment by xzhuz** [comment]
我的图标都是从https://www.iconfont.cn/上面下载的编译包。

**Comment by mytianya** [comment]
我想在你的基础上直接加，不然我要iconfont上面一个图标，一个图标的找，那样太麻烦了

**Comment by thetbw** [comment]
可以使用百度的这个fontedit，导入旧的字体，然后增加新的，重新导出
https://kekee000.github.io/fonteditor/index.html#

**Comment by xzhuz** [comment]
> 

你需要什么图标吧，把链接发出来。或者直接用 svg 都可以

**Comment by mytianya** [comment]
已解决
