### ISSUE TITLE
关闭全屏图片，卡片随机图片加载问题

### ISSUE THREAD

**Issue by qichanna** [xzhuz/halo-theme-xue#125]
Hi，你好：
              发现一个问题，我设置了随机图片，当以卡片风格展示，并且把首页全屏图片关闭的时候，每次新打开主页的时候(刷新好像没问题)，卡片的图片就只显示loading的动画，一定要滚到一下，才会加载出图片，不知道这是不是bug

**Comment by ruibaby** [comment]
没有复现，目前还有这个问题吗？
