### ISSUE TITLE
文章内容无法查看

### ISSUE THREAD

**Issue by Alone7707** [xzhuz/halo-theme-xue#131]
![QQ截图20210201104317](https://user-images.githubusercontent.com/63057446/106409271-23d74e80-647b-11eb-8eaa-7c5369c9b589.png)

一直在转，控制台报错 
![微信图片_20210201104454](https://user-images.githubusercontent.com/63057446/106409277-2639a880-647b-11eb-8070-b15f8d7052b4.png)

**Comment by xzhuz** [comment]
你的网站是什么呢？

**Comment by Alone7707** [comment]
> 你的网站是什么呢？

https://blog.a3-507.top/

**Comment by Xuzhengk** [comment]
我也出现了这个问题，控制台报了这个错误Uncaught ReferenceError: enableCodeHighlight is not defined，查看页面元素，其实文章内容是有的，但样式被设置了display:none。更换其他主题后，该问题消失。

**Comment by ruibaby** [comment]
https://github.com/xzhuz/halo-theme-xue/issues/170#issuecomment-960425140
