### ISSUE TITLE
BUG : LaTeX 渲染有误

### ISSUE THREAD

**Issue by RicrodoZ** [xzhuz/halo-theme-xue#133]
### 原文链接

[Link](https://blog.buckbit.top/2020/12/19/random-and-top-k-question)

### 描述

  ```
  依此类推，可得选择任一元素（设其下标为 $j$ ）的概率为 $\frac{1}{j}*(1-\frac{1}{j+1})*...*(1-\frac{1}{i-1})*(1-\frac{1}{i})=\frac{1}{i}$ 故该算法可以确保选择出的元素的随机性。
  ```

Halo 后台渲染无误，但前端渲染失败，如图：

![image](https://user-images.githubusercontent.com/44362358/107133266-5ffa2b80-6921-11eb-9fbc-73eb372f94ac.png)

### 一种可行的方案

我觉得其实可以将原文中的所有 LaTeX 代码都托管给 [Online LaTeX Equation Editor - create, integrate and download](https://latex.codecogs.com/) 渲染，然后在后台配置请求链接的参数，这样就可以避免出现本地渲染失败的问题

**Comment by MakiseVon** [comment]
![](https://i.loli.net/2021/02/08/KZh9wIoDxs1OpC7.png)

**Comment by MakiseVon** [comment]
建议使用 master 分支的版本再试试。

**Comment by RicrodoZ** [comment]
> 建议使用 master 分支的版本再试试。

每一个更新的包我都试过了，或多或少出现渲染错误的问题

原文本我放在奶牛快传了[Link](https://cowtransfer.com/s/82163cc3c72c47)，方便进行测试

**Comment by MakiseVon** [comment]
![](https://i.loli.net/2021/02/08/UdV9DGExyR3mgZN.png)
你是下载的 release 的 zip 包吧？直接 Clone repo 压缩后使用。

**Comment by RicrodoZ** [comment]
谢谢，问题解决了
