### ISSUE TITLE
上一篇和下一篇文章的图片不能显示

### ISSUE THREAD

**Issue by eelve** [xzhuz/halo-theme-xue#135]
![图片](https://user-images.githubusercontent.com/13844973/107851282-c3192000-6e43-11eb-8c5f-6748c5e0a52d.png)
![图片](https://user-images.githubusercontent.com/13844973/107851319-11c6ba00-6e44-11eb-8a31-effd55b7fd6e.png)

**Comment by kehongcheng** [comment]
在上一篇中，看img的src属性，图片地址是获取到了的，但是后面少了个双引号，去后台改代码，作者少加了个双引号，加上去就有图片了。
![捕获](https://user-images.githubusercontent.com/52595046/118634334-fd100e80-b804-11eb-97d7-6b5aa8b0dc4a.PNG)
下一篇并没有丢失双引号，但是img的class为lazyloaded，改为lazyload就行了。
