### ISSUE TITLE
code渲染问题

### ISSUE THREAD

**Issue by hb0730** [xzhuz/halo-theme-xue#136]
当使用多行代码块\``` \```时，内容存在其他符合时，存在渲染错误，如：
\```shell
[root@centos7 tomcat]# vim docker-compose.yml
version: '3'
services:
  tomcat:
    restart: always
    image: tomcat
    container_name: tomcat
    ports:
     -  8080:8080
\```
需要使用 `\` 进行转义，不管使用什么代码风格都是如此:
```shell
[root@centos7 tomcat]# vim docker-compose.yml
version: '3'
services:
  tomcat:
    restart: always
    image: tomcat
    container_name: tomcat
    ports:
     \-  8080:8080
```

**Comment by hb0730** [comment]
开启了idea代码风格

**Comment by hb0730** [comment]
不管是否开启代码高亮，展示行号，更改代码高亮，idea代码风格，都无效

**Comment by AaronFeng33** [comment]
以$开头的渲染也有问题，有点难受。

**Comment by AaronFeng33** [comment]
并且$转义都没用

**Comment by ruibaby** [comment]
https://github.com/xzhuz/halo-theme-xue/issues/170#issuecomment-960425140
