### ISSUE TITLE
【BUG】日志页面显示时间错误

### ISSUE THREAD

**Issue by mimajiushi** [xzhuz/halo-theme-xue#137]
![image](https://user-images.githubusercontent.com/33995610/108586705-1d0d6e80-738b-11eb-83ec-c2dccabf1c03.png)

**Comment by mimajiushi** [comment]
版本是1.2.3

**Comment by zhuangjy24** [comment]
同遇到相同问题

**Comment by sfafasfs** [comment]
这个问题可以这样解决：找到journals.ftl文件，把32行改成
<span class="ziyan-date" >${journal.createTime?string('yyyy-MM-dd HH:mm:ss')}</span>
估摸着应该是日期渲染的问题
![image](https://user-images.githubusercontent.com/51731248/109586176-b84ad480-7b3f-11eb-9bfc-879ed1492fc0.png)

**Comment by zzzgd** [comment]
> 这个问题可以这样解决：找到journals.ftl文件，把32行改成
> ![image](https://user-images.githubusercontent.com/51731248/109586278-e29c9200-7b3f-11eb-9559-058ba5954e49.png)
> 估摸着应该是日期渲染的问题
> ![image](https://user-images.githubusercontent.com/51731248/109586176-b84ad480-7b3f-11eb-9bfc-879ed1492fc0.png)

这个同时解决了24小时制的坑, 原本是12小时导致时间线错乱
