### ISSUE TITLE
markdown数学公式编辑实时预览和博客页面样式不一致

### ISSUE THREAD

**Issue by zhaojun0193** [xzhuz/halo-theme-xue#144]
![image](https://user-images.githubusercontent.com/21002594/111285561-3c42a780-867c-11eb-96ea-de1bf900b661.png)
这是在文章编辑实时预览时的公式样式

![image](https://user-images.githubusercontent.com/21002594/111285412-13baad80-867c-11eb-90ba-3b82c68f06ef.png)
这是在博客页面上显示的公式

在博客页面上公式被压缩成一行了。这个应该怎么解决呢？

[有问题的文章页面](https://www.zhaojun.ink/archives/36)

**Comment by ruibaby** [comment]
https://github.com/xzhuz/halo-theme-xue/issues/170#issuecomment-960425140
