### ISSUE TITLE
Markdown语法问题

### ISSUE THREAD

**Issue by 15536818056** [xzhuz/halo-theme-xue#146]
您好，之前没有出现如下问题，但是今天写博客的时候发现
① 在博客中使用html形式展示图片 <img src="" width=80%>不会显示图片而是显示源代码
② 在代码块中的单引号会被转义成&#x27;
<img width="215" alt="fankui" src="https://user-images.githubusercontent.com/72532185/113707392-6aaf2200-9712-11eb-9d79-90a9218911ef.png">

**Comment by ruibaby** [comment]
https://github.com/xzhuz/halo-theme-xue/issues/170#issuecomment-960425140
