### ISSUE TITLE
报Bug:日志页不能显示日志发表的时间。

### ISSUE THREAD

**Issue by aRuul** [xzhuz/halo-theme-xue#153]
- 所使用的主题版本：[1.2.3-halo-theme-xue.bugfix.1.zip](https://github.com/xzhuz/halo-theme-xue/releases/download/1.2.3/halo-theme-xue.bugfix.1.zip)
- 显示如下：
![image](https://user-images.githubusercontent.com/66399688/118776693-d6141400-b8ba-11eb-8e42-4ad38300c1ec.png)

**Comment by wukong86372** [comment]
我也是这样，老哥解决了吗

**Comment by zzzgd** [comment]
https://github.com/xzhuz/halo-theme-xue/issues/161#issue-924628277 @wukong86372 可能是和我一样的情况, 24小时制

**Comment by zzzgd** [comment]
https://github.com/xzhuz/halo-theme-xue/issues/137#issuecomment-863827290 这个老哥给出了解决方法
