### ISSUE TITLE
进入首页时，缩略图未正常加载

### ISSUE THREAD

**Issue by lifeorwar** [xzhuz/halo-theme-xue#157]
![image](https://user-images.githubusercontent.com/21236400/120491264-af41fb80-c3eb-11eb-847b-b9042a8b1152.png)
操作步骤：
1. 通过导航栏进入"文章归档"页面
2. 进入"文章归档"页面后通过导航栏进入“首页”

主题版本：1.2.3

**Comment by lifeorwar** [comment]
![image](https://user-images.githubusercontent.com/21236400/120651735-a9aee900-c4b1-11eb-8829-d22e9b1a6bd1.png)
实测与pajax开启有关系，首次加载时触发了check();方法，页面切换时未触发，关闭pajax后正常

**Comment by ruibaby** [comment]
我这边没有复现。
