### ISSUE TITLE
文章目录加载失败，控制台有console error

### ISSUE THREAD

**Issue by lifeorwar** [xzhuz/halo-theme-xue#158]
偶发性，刷新多次时、从首页重新进入文章时可能会发生，表现如下（目录未正常展示）
![image](https://user-images.githubusercontent.com/21236400/120491987-460eb800-c3ec-11eb-9df8-ea138b7eba22.png)
正常应该是这样的
![image](https://user-images.githubusercontent.com/21236400/120492269-8110eb80-c3ec-11eb-8add-f998f0376baf.png)
控制台日志如下（滚动事件时会触发日志输出）：
![image](https://user-images.githubusercontent.com/21236400/120493197-52dfdb80-c3ed-11eb-867f-c77ef40e0923.png)

主题版本：1.2.3

**Comment by xzhuz** [comment]
这种情况应该是偶发性，我并没有浮现这种情况

**Comment by xzhuz** [comment]
你是不是自定义了 tocbot 的 linkClass
