### ISSUE TITLE
图片展示问题

### ISSUE THREAD

**Issue by zzzgd** [xzhuz/halo-theme-xue#160]
https://zzzgd.info/photos

一开始没发现, 以为是需要管理员和写文章一样发图片才有, 但是也没找到发图片的地方, 应该就是展示上传的附件? 后面发现确实是没有
我就只加了一个查看访问地图的js, 和一个2dlive的js 

不清楚是halo那边的bug还是主题这边的问题, 所以两边都问下 ==

**Comment by EdgarDing77** [comment]
你说的相册功能，在页面-所有页面-相处-管理，没有被单独提取出来放入到仪表板中
