### ISSUE TITLE
作者您好，我使用的您的主题,发现编写文章的时候 $符号会出现html代码导致不能正常显示,请问这个问题是需要怎么去解决的呢？

### ISSUE THREAD

**Issue by xq-soliton** [xzhuz/halo-theme-xue#163]

**Comment by isSelf** [comment]
我也是这个问题，在输入latex公式的时候，会出现解析不出来的情况，然后导致整篇文章都不能正常显示。

**Comment by ruibaby** [comment]
https://github.com/xzhuz/halo-theme-xue/issues/170#issuecomment-960425140
