### ISSUE TITLE
文章列表分类不显示的问题

### ISSUE THREAD

**Issue by codeyee** [xzhuz/halo-theme-xue#167]
文章列表在显示文章的“分类”时只能显示一级分类，如果归属于二级分类则不显示

![image](https://user-images.githubusercontent.com/43313765/130311483-bea255e3-535a-42ad-82fc-0292a519a5eb.png)

**Comment by ruibaby** [comment]
这应该属于 Halo 的问题，目前似乎已经修复。 https://github.com/halo-dev/halo-admin/pull/367
