### ISSUE TITLE
Bug:  由 JQuery.js 的 replaceAll() 兼容性问题导致无法渲染文章内容

### ISSUE THREAD

**Issue by codeyee** [xzhuz/halo-theme-xue#168]
问题复现：

- 在安卓版 chrome 78.x 的情况下，文章内容中出现由 markdown 编写的公式，会提示  “replaceAll is not a function”

- 详细的复现过程参考这篇博文：[从 “replaceAll is not a function” 中复盘 JQuery.js 兼容性问题](https://codeyee.com/archives/jquery-replaceall-not-found.html)

解决方案：

- 使用 RegExp 结合 replace 实现 replaceAll 的效果，实现更好的兼容性。

**Comment by kingqh** [comment]
如何解决的？

**Comment by xzhuz** [comment]
可以先不关注这个issue，后面可能直接用后端渲染的html
