### ISSUE TITLE
Bug：行内公式正则兼容问题

### ISSUE THREAD

**Issue by codeyee** [xzhuz/halo-theme-xue#169]
- 行内公式使用 `/\$([\s\S]*?)\$/g` 进行匹配，会导致整个文章内容如果两处地方（非同一行）出现两次 `$` 字符的情况下会被匹配为行内公式进行处理。
- 如果文章中出现 `\$xxx\$` 的内容也会被当作行内公式处理

解决方案：将 `/\$([\s\S]*?)\$/g` 替换为 `/\$(?!\\$)(.*?)\$(?!\\$)$/g` ，即可处理上述的两种情况。

> 可能不是最佳的方案，因为不经常使用 markdown 来写公式，可能会导致部分公式没有被匹配到。

**Comment by ruibaby** [comment]
https://github.com/xzhuz/halo-theme-xue/issues/170#issuecomment-960425140
