### ISSUE TITLE
文章随机图无法使用

### ISSUE THREAD

**Issue by leekihom** [xzhuz/halo-theme-xue#175]
文章随机图无法显示，看后代码发现是data-src=“”，感觉是没有被赋值导致的，具体应该怎样修改呢？后台的随机图片配置了也没用，前台还是显示src(unknow)

![74558FDC-8F1C-4ca6-85EB-9F234A0C5B08.png](https://i.loli.net/2021/10/19/Xw74keD8V3qBKHO.png)
![0BBCCC27-2C6B-4792-8984-117570238C07.png](https://i.loli.net/2021/10/19/AkrClmBVdewPfDh.png)

**Comment by ruibaby** [comment]
请问你的配置是怎样的，我这边测试是没有问题的。
