### ISSUE TITLE
首页，热门文章伪类有点问题

### ISSUE THREAD

**Issue by wsqGIT** [xzhuz/halo-theme-xue#176]
博客地址 https://www.cokecoke.top

问题：首页，热门文章伪类有点问题，鼠标悬停才会显示；全局图片无效

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/50320009/138541283-384f711e-a862-4dae-8320-5773e01db3d5.png">

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/50320009/138541327-e93f908d-6870-4cac-b3e0-3d113a7ceda2.png">

**Comment by ruibaby** [comment]
我这边是正常的，你那边还有这样的问题吗？
