### ISSUE TITLE
文章正文刷新不出来

### ISSUE THREAD

**Issue by MiaoXXSSE** [xzhuz/halo-theme-xue#177]
js报错 marked is not a function之类的错误

好像是因为marked.js版本升级的原因，marked(xxx)的方法没了，要通过marked.parse(xxx)的方式去使用，我按照如下方式改了之后能正常查看页面了：

source/js/main.js

persentContent.html(marked(originalContent.trim()));

**Comment by ruibaby** [comment]
能帮忙提交一个 pr 吗？

**Comment by MiaoXXSSE** [comment]
已提pr，marked.js3天前（2021-11-02）出的4.0.0版本的变更：When using marked in a script tag use marked.parse(...) instead of marked(...)
