### ISSUE TITLE
文章评论的回复怎么默认打开？

### ISSUE THREAD

**Issue by syniii** [xzhuz/halo-theme-xue#185]
文章评论的回复怎么默认打开？现在回复默认是收起来的，必须点更多才能显示出来...

**Comment by ruibaby** [comment]
你可以换一个评论组件 https://github.com/search?q=topic%3Ahalo-comment-component+org%3Ahalo-dev&type=Repositories

**Comment by syniii** [comment]
@ruibaby 已解决，感谢
