### ISSUE TITLE
下一页出现了错误

### ISSUE THREAD

**Issue by li-yu-kun** [xzhuz/halo-theme-xue#187]
我换了halo默认主题是没问题的。而且这个错误只在这个主题中设置 首页文章列表展示风格中更换为列表的时候会出错，卡片不会出错。

我的网站shentu.run  首页中点击下一页会报这个错误 Access to XMLHttpRequest at 'https://www.shentu.run/page/2' from origin 'https://shentu.run' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by li-yu-kun** [comment]
请大佬指点这是我配置错误了还是哪里的问题呀？

**Comment by ruibaby** [comment]
请保持你所访问的域名和在后台设置的域名一致。

**Comment by li-yu-kun** [comment]
谢谢大佬；已解决
