### ISSUE TITLE
cdn.jsdelivr.net  这个经常打不开，没有人管吗？

### ISSUE THREAD

**Issue by syniii** [xzhuz/halo-theme-xue#191]
cdn.jsdelivr.net  这个经常打不开，就不能全换成本地的或者稳定的cdn？

**Comment by ruibaby** [comment]
可以先下载 master 分支进行更新：https://github.com/xzhuz/halo-theme-xue/archive/refs/heads/master.zip

**Comment by syniii** [comment]
@ruibaby  终于修复了，感谢
