### ISSUE TITLE
cdn.jsdelivr.net网络已经出现问题，能否将静态资源文件本地化 静态资源加载很慢~

### ISSUE THREAD

**Issue by niujinkai** [xzhuz/halo-theme-xue#192]
cdn.jsdelivr.net网络已经出现问题，能否将静态资源文件本地化
静态资源加载很慢~
![image](https://user-images.githubusercontent.com/97371434/148951408-e5ee4336-de5f-42be-b7f2-dd70cd6a05e6.png)

**Comment by ruibaby** [comment]
可以先下载 master 分支进行更新：https://github.com/xzhuz/halo-theme-xue/archive/refs/heads/master.zip

**Comment by ruibaby** [comment]
> @ruibaby 更新了  是把资源已经静态化了嘛？

全部放在主题里面了，可以自行优化。
