### ISSUE TITLE
文章页的代码风格，能否加多几个风格

### ISSUE THREAD

**Issue by zyy24796143** [xzhuz/halo-theme-xue#196]
![image](https://user-images.githubusercontent.com/25009398/153536071-49cf71b8-e185-4f9c-8ebd-dec0f5eb69cd.png)

貌似这个主题的代码风格都比较简单，颜色比较单一，看起来比较抓狂，就像这样。能否调整一下代码块的风格？

**Comment by xzhuz** [comment]
目前暂时不考虑，但是使用者而已自定义样式
