### ISSUE TITLE
能否标题栏可以添加一下二级抽屉目录功能，谢谢了

### ISSUE THREAD

**Issue by xiehaoing** [xzhuz/halo-theme-xue#197]
能否标题栏可以添加一下二级抽屉目录功能，谢谢了

**Comment by xzhuz** [comment]
二级抽屉目录功能？什么样子的呢

**Comment by xiehaoing** [comment]
大概就是这个样子的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiao ***@***.***&gt;; 
发送时间: 2022年2月21日(星期一) 下午3:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xzhuz/halo-theme-xue] 能否标题栏可以添加一下二级抽屉目录功能，谢谢了 (Issue #197)





 
二级抽屉目录功能？什么样子的呢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiehaoing** [comment]
[![微信截图_20220221155829.png](http://tc.naspro.cc/2022/02/21/a8be5d15d358d.png)](http://tc.naspro.cc/2022/02/21/a8be5d15d358d.png)

大概这个样子

**Comment by xzhuz** [comment]
目前两个版本没有这个计划，你可以期待一下后续的版本

**Comment by Extrwave** [comment]
虽说看见了更新，具体怎么实现呢？这边后台只有分类可以支持从属关系，菜单并没有找到

**Comment by xzhuz** [comment]
可以在菜单设置哪儿推动菜单即可

**Comment by Extrwave** [comment]
是更新的问题嘛？如此设置之后并没有看见二级菜单，[传送门](https://blog.ethreal.cn)![](https://cdn.jsdelivr.net/gh/Extrwave/IMAGE@master/blogclick/16499437774441649943776834.png)

**Comment by xzhuz** [comment]
还没发布新版本
