### ISSUE TITLE
代码块样式缺少内边距会使代码块很起来很挤

### ISSUE THREAD

**Issue by guqing** [xzhuz/halo-theme-xue#203]
代码块样式缺少内边距使代码样式看起来很挤，如果加一个 padding:15px;会好看很多
<img width="666" alt="image" src="https://user-images.githubusercontent.com/38999863/157826089-8fe5d2e9-2163-47fb-ad34-78add579bb22.png">

**Comment by xzhuz** [comment]
最新版本会加上这个，尽情期待

**Comment by xzhuz** [comment]
> 最新版本会加上这个，尽情期待

你可以pull最新的master代码，已经加上内边距了

**Comment by guqing** [comment]
> > 最新版本会加上这个，尽情期待
> 
> 你可以pull最新的master代码，已经加上内边距了

好的 辛苦啦👏👏
