### ISSUE TITLE
夜晚模式问题

### ISSUE THREAD

**Issue by AnotiaWang** [xzhuz/halo-theme-xue#204]
应该是有两处问题。

### 复现步骤
1. 在主题设置中关闭 “自动夜晚模式”
2. 在主题设置中启用 “开启夜晚模式”
3. 使用浏览器访问博客，调整为夜晚模式
4. 在主题设置中关闭 “开启夜晚模式”
5. 刷新博客页面

### 预期现象
博客应该是浅色模式

### 实际现象
博客仍为深色模式

### 复现步骤
1. 在博客设置中启用 “自动夜晚模式”
2. 将浏览器主题调整为浅色，访问博客
3. 将浏览器主题调整为深色，刷新博客页面，此时博客自动切换为深色，没有问题
4. 将浏览器主题调整回浅色，刷新博客页面

### 预期现象
步骤 4 中，博客应当自动切换回浅色

### 实际现象
博客仍然为深色

## 博客版本

[f15dce1](https://github.com/xzhuz/halo-theme-xue/commit/f15dce19f54338c6c8bc8df85a25b6f3df06c62d)

## 补充

问题二使用 Edge 测试。以下是另外一点想法：

“开启夜晚模式” 这个选项，应该是针对全局吧？也就是说关闭此选项，应该会禁用整个博客的深色主题。但是测试的时候，如果开启了自动切换，那么在深色浏览器主题下，博客还是会切换成夜晚模式的。不知道是不是设置面板的表述不够清楚。

**Comment by AnotiaWang** [comment]
还有个问题，开启自动切换的情况下，在博客内手动调整了主题，刷新还是会变回来

**Comment by xzhuz** [comment]
关于你前面两个问题，目前深色模式使用的浏览器的 localstorage ，也就是本地缓存。以上两个问题出现的主要原因是，你在切换到深色模式之后，以及在 localstorage 中保存了对应的状态，并且关闭深色模式只是不显示按钮。所以你在切换深色模式之后，即使你关闭深色模式，再次刷新也会是深色模式，不会是浅色模式。

**Comment by xzhuz** [comment]
目前最新版本的计划是，没有自动深色模式这个开关，也没有深色模式开关。所以一般不会存在这个问题。

**Comment by AnotiaWang** [comment]
> 目前最新版本的计划是，没有自动深色模式这个开关，也没有深色模式开关。所以一般不会存在这个问题。

明白了，谢谢

**Comment by xzhuz** [comment]
可以看下最新版本

**Comment by AnotiaWang** [comment]
不过最新版有两个问题（与本 issue 无关）

一个是浏览器的字号比较大的时候，文章的目录字体会和其它元素重叠，如下图 ↓
浏览器 Chrome，字号 18，网页缩放 100%

![image](https://user-images.githubusercontent.com/62269186/160513199-e7d8b6e7-1c4f-4b84-9337-6a8333cbf32a.png)

另外一个疑问是，新版页面右下角的按钮似乎变了，现在只剩下一键回顶的功能，请问是新版本的计划特性吗？按钮的动画似乎有点问题，页面滚动的时候按钮会先闪过三个点的图标，然后变成上箭头。

![image](https://user-images.githubusercontent.com/62269186/160513372-6d8f6546-33be-4dfc-9128-a29a9f51397a.png)

**Comment by xzhuz** [comment]
> 不过最新版有两个问题（与本 issue 无关）
> 
> 一个是浏览器的字号比较大的时候，文章的目录字体会和其它元素重叠，如下图 ↓ 浏览器 Chrome，字号 18，网页缩放 100%
> 
> ![image](https://user-images.githubusercontent.com/62269186/160513199-e7d8b6e7-1c4f-4b84-9337-6a8333cbf32a.png)
> 
> 另外一个疑问是，新版页面右下角的按钮似乎变了，现在只剩下一键回顶的功能，请问是新版本的计划特性吗？按钮的动画似乎有点问题，页面滚动的时候按钮会先闪过三个点的图标，然后变成上箭头。
> 
> ![image](https://user-images.githubusercontent.com/62269186/160513372-6d8f6546-33be-4dfc-9128-a29a9f51397a.png)

第一个问题：你是自定义了Chrome浏览器字号吗？如果是自定义的，这就需要使用者自己适配。
第二个问题：是现在的新特性，我正在逐渐将右下角的按钮简化，后期可能只会有一个一键置顶的功能

**Comment by AnotiaWang** [comment]
> 第一个问题：你是自定义了Chrome浏览器字号吗？如果是自定义的，这就需要使用者自己适配。

确实是自己改的，因为默认字体有点小看不清😂请问怎么适配呢


> 第二个问题：是现在的新特性，我正在逐渐将右下角的按钮简化，后期可能只会有一个一键置顶的功能。目前可能存在一些小问题，这个问题后期我也会看看怎么优化

明白了，谢谢

**Comment by xzhuz** [comment]
如果确实你自己改的浏览器的字体，主题暂不考虑做适配
