### ISSUE TITLE
主题资源当中缺少备案图标ico，辛苦在主题包中添加下！

### ISSUE THREAD

**Issue by niujinkai** [xzhuz/halo-theme-xue#205]
主题资源当中缺少备案图标ico，辛苦在主题包中添加下！
![image](https://user-images.githubusercontent.com/97371434/158020198-5f0b2b55-2f3c-4fff-8e22-e307ae004784.png)

**Comment by manction** [comment]
确实是缺少图标文件

**Comment by niujinkai** [comment]
> 确实是缺少图标文件

嗯嗯，希望处理下
