### ISSUE TITLE
文章页代码块颜色错误

### ISSUE THREAD

**Issue by hashi0** [xzhuz/halo-theme-xue#206]
无法选择代码高亮主题，颜色太深与背景色混淆
<img width="758" alt="image" src="https://user-images.githubusercontent.com/47022972/158025649-c179a5ea-71d2-46f0-8e77-b67291032c25.png">

**Comment by xzhuz** [comment]
目前最新版本计划都是黑色模式，你可以去我的网站看看最新的样式。还有个原因，可能是不支持hadoop 代码

**Comment by hashi0** [comment]
> 

这个是shell命令不是hadoop代码。
目前的黑色模式下，markdown代码块无法识别的语法会默认给一个容易混淆的灰色；但是有些语言markdown不一定能够完全识别高亮，导致整个代码看不到，哪里可以改下代码块背景色为浅色模式吗？

**Comment by hashi0** [comment]
在贵站看了下shell的代码块，相比我的样式更清晰，字号也跟大
我尝试过`更换不同的代码风格`以及`开关IDEA代码风格`，还是无法达到和图中一样的效果，请问下这个是样式是如何做到的呢？
![image](https://user-images.githubusercontent.com/47022972/158062196-43ea65e3-3bc4-4fcf-b757-7c29f7fe430b.png)


我的样式：
![image](https://user-images.githubusercontent.com/47022972/158062225-7963df4e-f18b-4516-a317-6556e2815a86.png)

**Comment by xzhuz** [comment]
我的网站是目前最新版本的preview。之前的版本可能存在一些小问题，所以在最新的版本中，我会将想这些问题一一修复。麻烦你耐心等待下一个版本，谢谢
