### ISSUE TITLE
怎么修改logo

### ISSUE THREAD

**Issue by conceay** [xzhuz/halo-theme-xue#211]
halo本来能自定义logo但是这个主题貌似不显示logo呢

**Comment by xzhuz** [comment]
不好意思，目前确实不支持 logo。

**Comment by conceay** [comment]
好，那什么时候会增加呢？还是说没有这个想法了

**Comment by xzhuz** [comment]
> 好，那什么时候会增加呢？还是说没有这个想法了

下个版本计划
