### ISSUE TITLE
更新1.3.2版本后主页文章图片不显示

### ISSUE THREAD

**Issue by IILee5** [xzhuz/halo-theme-xue#222]
![image](https://user-images.githubusercontent.com/40862062/160068141-83a69426-fa02-4d68-9866-161ec725133f.png)
站点地址：[https://blog.iilee.cn](https://blog.iilee.cn/)

**Comment by xzhuz** [comment]
这是个 bug，目前已修复，重新上传了[zip](https://github.com/xzhuz/halo-theme-xue/releases/download/1.3.2/halo-theme-xue.zip) 包，重新下载即可。也可以拉去最新的 master 代码

**Comment by IILee5** [comment]
您好，我将您回复里面的包体下载后问题依旧存在（已清除浏览器缓存、cdn缓存），不知道我这个问题是否为特例🤕

**Comment by Extrwave** [comment]
这边也看不见，可以检查你自己的图片外链是否失效，或者随机API调用失败

**Comment by xzhuz** [comment]
> 您好，我将您回复里面的包体下载后问题依旧存在（已清除浏览器缓存、cdn缓存），不知道我这个问题是否为特例🤕

可否给一个你的网站连接。

**Comment by xzhuz** [comment]
> 您好，我将您回复里面的包体下载后问题依旧存在（已清除浏览器缓存、cdn缓存），不知道我这个问题是否为特例🤕

看你的网站，不是用的最新的主题包。如果你说用的是回复包，你可以对比下你网站的 main.js 文件和包里面的 main.js 文件，明显不一样。你可以检查下 cdn 是否更新成功和主题包是否更新成功

**Comment by IILee5** [comment]
可以了，谢谢您😄️
