### ISSUE TITLE
1.32版本更新后有些选项缺失

### ISSUE THREAD

**Issue by laffitto** [xzhuz/halo-theme-xue#223]
您好，一直很喜欢您做的主题，今天更新halo版本和主题后发现是不是有一些原始的选择项消失了，比如夜间模式，不显示头图，右下角点击展开显示等等。可以上我的网站看一下：https://laffitto.xyz/
请问后续是否会添加回来呢，还是说是我这边的问题呢
![image](https://user-images.githubusercontent.com/52039038/160076143-59e0aa42-9482-43ea-82c3-84637bcf78ce.png)

**Comment by xzhuz** [comment]
感谢你的支持。1.3.2 版本的主题对一些功能配置做了简单化，删除了诸如深色模式、右下角按钮等配置。这些功能都集成到主题中。
目前主题的发展方向是，能在功能完善的技术上，最大的简单化，做到化繁为简。也希望后续你的继续支持，也期待您的反馈和建议。

**Comment by laffitto** [comment]
谢谢作者的解答，主要是1.3.2下主题似乎缺失了类似搜索等功能，且相较于上一版改动较大（添加了点赞，阅读统计等，且移动端布局与桌面端有点不统一），跨度有点大，一时难以适应。

**Comment by xzhuz** [comment]
搜索功能目前还是有的，你可以看我的网站。我的网站基本上把所有功能都用上的
