### ISSUE TITLE
1.3.2怎么无法设置代码高亮

### ISSUE THREAD

**Issue by DAMYSDS** [xzhuz/halo-theme-xue#224]

**Comment by xzhuz** [comment]
主题本身就支持代码高亮，不需要单独的开关

**Comment by DAMYSDS** [comment]
> 主题本身就支持代码高亮，不需要单独的开关
我意思是一些开关是取消了吗，我是从1.0升级的1.3.2

**Comment by xzhuz** [comment]
你好，目前的开关取消了。
开发过程中，我认为默认开启即可。且在主题使用中，如不需要代码高亮，主题也不会渲染
