### ISSUE TITLE
文章页面右边侧栏标题定位

### ISSUE THREAD

**Issue by Extrwave** [xzhuz/halo-theme-xue#228]
# 标题
### 标题
类似这种标题的右边目录定位不准确，可以找找原因吗？
[传送门](https://blog.ethreal.cn/archives/datatype)

**Comment by Extrwave** [comment]
基本上需要连续点击好几次才会跳转

**Comment by xzhuz** [comment]
主要原因是你的标题中存在的`、`号造成了转义，跳转

**Comment by Extrwave** [comment]
> 、

好的，我会尝试避免此类标题，期待你的修复

**Comment by Extrwave** [comment]
哦对了，我尝试更改标题去掉了`、`，但仍然存在此问题，供参考

**Comment by xzhuz** [comment]
目前还存在这个问题吗？

**Comment by Extrwave** [comment]
你好，在替换掉标题后，仍然存在此问题（昨天晚上已经更新主题与仓库一致）
[传送门](https://blog.ethreal.cn/archives/datatype)

**Comment by xzhuz** [comment]
![image](https://user-images.githubusercontent.com/23736683/160317104-fb65ee17-1733-4e2f-b888-98677173bfbf.png)
![image](https://user-images.githubusercontent.com/23736683/160317128-39de9e55-7c5f-4e80-b255-b3d6e1370a93.png)
你可以 对比这两个地方，很明显不一样。这也是问题的原因所在，后期会做修复。

**Comment by Extrwave** [comment]
也就是中文标题都会出现这个问题，期待你的修复

**Comment by xzhuz** [comment]
其实也不是中文标题会出现这个问题，我也是用的中文标题，就没有出现这个问题。我认为很有可能是汉字加数字或特殊字符会出现这个问题
