### ISSUE TITLE
关于搜索框按钮无法点击情况

### ISSUE THREAD

**Issue by Extrwave** [xzhuz/halo-theme-xue#229]
如图，是不是布局哪儿出问题了，还是浏览器个例？目前 Microsoft Edge
[如图](https://cdn.jsdelivr.net/gh/Extrwave/IMAGE@master/blogclick/16484323981981648432397472.png)

**Comment by xzhuz** [comment]
你把你的网站发我看下

**Comment by Extrwave** [comment]
[网站](https://blog.ethreal.cn)

**Comment by xzhuz** [comment]
https://github.com/xzhuz/halo-theme-xue/releases/tag/1.3.2.hotfix
你下载这个release中的包

**Comment by Extrwave** [comment]
OK，成功解决，后续可以直接在线更新吗？

**Comment by xzhuz** [comment]
后续直接用master代码就可以
