### ISSUE TITLE
友情链接默认用户头像 不生效

### ISSUE THREAD

**Issue by zyy24796143** [xzhuz/halo-theme-xue#230]
在 1.3.2 版下，“友情链接默认用户头像”的默认图片地址，在国内网络打不开。添加url 后，结果在“友情链接页面默认头部图” 的位置生效了。在“友情链接页面默认头部图” 添加url后，却没有生效。

**Comment by xzhuz** [comment]
没有特别懂什么意思

**Comment by zyy24796143** [comment]
[就是我在“友情链接默认用户头像：”里添加了(https://s2.loli.net/2022/03/28/15IX4xmdzwDueK8.jpg) 这个图片，然后好像在“友情链接页面默认头部图：”生效了。   ![image](https://user-images.githubusercontent.com/25009398/160967870-3d171478-2bc2-46f7-9288-16fe4479e375.png)
![image](https://user-images.githubusercontent.com/25009398/160968057-eab1868e-0847-47c9-b319-ede61672ddc8.png)
