### ISSUE TITLE
后台文章可以看见格式没有问题，但是前台无法解析，直接显示了

### ISSUE THREAD

**Issue by Zzznopay** [xzhuz/halo-theme-xue#235]
后台显示：
![后台显示](https://user-images.githubusercontent.com/49267799/161066351-6c2e1d90-9bb5-46d1-b7f2-a9d9e49ea7e5.png)
前端预览：
![前端预览](https://user-images.githubusercontent.com/49267799/161066498-9b035b91-fd90-4d9d-a60d-c6900bd83d2b.png)

**Comment by xzhuz** [comment]
用的最新的版本吗？

**Comment by xzhuz** [comment]
新版本应该是不会这样子的
