### ISSUE TITLE
Xue 1.3.2.hotfix 问题反馈

### ISSUE THREAD

**Issue by manction** [xzhuz/halo-theme-xue#236]
主页：[月光海岸](https://www.manction.com)
网址：[https://www.manction.com](https://www.manction.com)
备注：首页使用卡片风格，后台关闭了全局 Pjax开关

目前版本：
Halo **1.5.1**
Xue **1.3.2.hotfix**

问题描述（或建议）：
1. 卡片图片没有加链接（个人感觉首页卡片部分，图片加上文章链接比较符合习惯，否则文字链接的热点区域太小，点击没有反应）
2. 标签没有加标签链接（首页列表风格却加了，这个版本我感觉到了作者对列表风格的偏爱）
3. 缺失了浏览量、评论数、发布日期等内容（因为我是发布原创摄影作品，所以需要首页展示更多图片信息）
4. 在后台开启了“**卡片风格首页是否展示文章简介**”选项，但是主页不显示文章简介
5. 底部分页样式上下边框间距没有对齐
6. 文章详情和日志页面新增了点赞功能，日志页面点赞后，点赞数会实时增加，但是图标没有变化，希望点赞后能有不同的样式效果进行区分；文章详情的点赞功能不生效；查看浏览器控制台，在文章详情和日志页面频繁点赞，似乎会产生大量重复请求，导致浏览器卡顿
7. 文章详情页，点击一次“点赞”按钮，会产生大量重复请求，而且api路径还不对（模板中是正确的）
8. 日志列表页面，个人建议没有必要出现两个user.nickname，因为主页的内容本来就是博主个人发布的
9. 底部公安备案缺少图标资源

**Comment by TanYongF** [comment]
好像夜间模式不能关闭？

**Comment by xzhuz** [comment]
> 好像夜间模式不能关闭？

不能关闭

**Comment by xzhuz** [comment]
@manction 
1、卡片模式加链接建议很好
2、标签链接也会加上
3、这个其实看个人喜好的，我觉得这些元数据并没有多少用。但我也会加一个配置项，可以开启或关闭
4、我不建议显示简介，这个会搞乱整个样式。我也没有计划做这个功能
5、这个 bug 会在下个版本修复
6、7、这两个问题也会在下个版本修复
8、好建议，我优化一下
9、下个版本修复

里面提到的很多问题，在开发版本里面已经修复了。如果你比较着急可以切换到开发版本

**Comment by TanYongF** [comment]
> > 好像夜间模式不能关闭？
> 
> 现在深色模式其实轻量很多了，没有必要加一个配置项 如果你确实不想要深色模式，你可以直接通过自定义 css 隐藏这个按钮

问一下如何修改配置，默认白天模式呀，找了找不知道从哪里下手，谢谢

**Comment by xzhuz** [comment]
> > > 好像夜间模式不能关闭？
> > 
> > 
> > 现在深色模式其实轻量很多了，没有必要加一个配置项 如果你确实不想要深色模式，你可以直接通过自定义 css 隐藏这个按钮
> 
> 问一下如何修改配置，默认白天模式呀，找了找不知道从哪里下手，谢谢

```css
.swap {
    display: none;
}
```
