### ISSUE TITLE
关于版权链接CSS优化一个小建议和请教

### ISSUE THREAD

**Issue by BFWFCOD** [xzhuz/halo-theme-xue#237]
一. 这个footer.ftl里的链接的主题，感觉“.badge-subject { padding:6px 4px 4px 6px; } ”和“ .badge-value { padding:6px 4px 4px 6px; } ”增加一点padding右边距更好看一点，例如改成：“ .badge-subject { padding:6px 8px 4px 6px; } ”、“ .badge-value { padding:6px 6px 4px 6px; } ”。

修改前：
![2](https://user-images.githubusercontent.com/52775944/161617169-51ef4ae0-95c2-42b7-ab33-c1cbe486418c.jpg)

修改后：
![1](https://user-images.githubusercontent.com/52775944/161617243-ff2e17e2-08a8-4dac-96f7-7ab4bbe53075.jpg)

二. 还有想请教作者大大，你的个人网站那种卡片信息是如何做的？例如标签在上、标题在中、日期信息在下这种更为和谐的排列，还有点击卡片的图片也可以跳转，但我的主题就不行。。

我的：
![3](https://user-images.githubusercontent.com/52775944/161617796-9a314da4-5974-491c-8d71-3722dc87cf80.jpg)

你的：
![4](https://user-images.githubusercontent.com/52775944/161617833-5e2b1204-3c5b-4f1b-af92-0ed44a81a548.jpg)

**Comment by xzhuz** [comment]
一、感谢你的建议，
二、目前我的网站是一个开发版本，这些功能都会在下个版本发布

**Comment by BFWFCOD** [comment]
> 一、感谢你的建议， 二、目前我的网站是一个开发版本，这些功能在下个版本发布

哦哦，感谢回复，期待作者大大更新
