### ISSUE TITLE
1.4.0 分页功能异常

### ISSUE THREAD

**Issue by manction** [xzhuz/halo-theme-xue#240]
名称：[月光海岸](https://www.manction.com)
网址：[https://www.manction.com](https://www.manction.com)

版本说明
Halo 1.5.1
Xue 1.4.0

问题描述：
无论在 **主题设置-高级功能** 中是否启用 **全局 Pjax**，分页插件的**上一页 <** 和 **下一页 >** 按钮点击都异常，无法正常跳转页面。点击数字按钮可以正常分页。

**Comment by xzhuz** [comment]
已修复
