### ISSUE TITLE
1.4.1  黑暗模式与文章目录不显示

### ISSUE THREAD

**Issue by eddie-code** [xzhuz/halo-theme-xue#247]
名称：[Eddie](https://blog.eddilee.cn/)
网址：https://blog.eddilee.cn/

版本说明
Halo 1.5.1
Xue 1.4.1

浏览器
火狐 98.0.2 (64 位）

问题描述：

- 列表风格下是否展示热门文章, 开启后没有出现。
- 博客主题打开默认变成黑暗模式，没有了关闭按钮？
- 是否展示目录已开，打开文章，没有显示目录。

**Comment by xzhuz** [comment]
1. 现在把热门文章这块去掉了，但是配置项没有删除
2. 清理一下本地缓存
3. 我看这边是有目录的
