### ISSUE TITLE
博文如何自定义上一篇和下一篇

### ISSUE THREAD

**Issue by loveferry** [xzhuz/halo-theme-xue#248]
我们这个主题可以自定义上一篇和下一篇么，怎么操作？

**Comment by xzhuz** [comment]
目前是不支持自定义的？你想自定义成那种

**Comment by loveferry** [comment]
比如说我的博文 “mysql（二）”，我想指定它的上一篇是 “mysql（一）”，下一篇是 “mysql（三）”，因为这三篇博文可能中间穿插这其他博文，这会导致默认的 “mysql（二）”的下一篇是 “oracle（一）”，类似这种情况

**Comment by ruibaby** [comment]
理论上这是需要 Halo 支持的。
