### ISSUE TITLE
请问能设置菜单图标吗

### ISSUE THREAD

**Issue by loongzcode** [xzhuz/halo-theme-xue#249]
请问能设置菜单图标吗？

**Comment by loongzcode** [comment]
还有一个问题，主页文章卡片的标签显示不完整，多个标签只会显示一个，还想请问下，评论的头像怎么搞

**Comment by xzhuz** [comment]
> 请问能设置菜单图标吗？

你可以在添加菜单名字那点加上图标的路径

**Comment by xzhuz** [comment]
> 还有一个问题，主页文章卡片的标签显示不完整，多个标签只会显示一个，还想请问下，评论的头像怎么搞

这是为了样式，只会显示一个标签。评论头像可以在下面的地方设置
![image](https://user-images.githubusercontent.com/23736683/162629347-abbb03d6-9cbb-48b3-b1ce-9fb90a98972b.png)

**Comment by manction** [comment]
> > 请问能设置菜单图标吗？
> 
> 你可以在添加菜单名字那点加上图标的路径

在外观-菜单设置中填写图标，主题不会生效，目前主题应该是不支持菜单图标功能。
基于Xue的个人站点：月光海岸 https://www.manction.com
