### ISSUE TITLE
1.4.1 版本友链中上面的头像能否更换一下url地址，貌似在国内的网络都打不开

### ISSUE THREAD

**Issue by zyy24796143** [xzhuz/halo-theme-xue#254]
1.4.1 版本友链中上面的头像能否更换一下url地址，cn.gravatar.com 貌似在国内的网络都打不开
![image](https://user-images.githubusercontent.com/25009398/162967713-6cc61b46-eb14-486a-ab20-2576e833a725.png)

**Comment by xzhuz** [comment]
这个是博客的头像地址，这是你自己设置的吗？

**Comment by zyy24796143** [comment]
不是，我博客头像地址都是 [s2.loli.net](https://s2.loli.net) 这个域名，可以打开的。
![image](https://user-images.githubusercontent.com/25009398/163657285-95387bb1-f78b-4d71-bf9c-3c97522259e2.png)

**Comment by xzhuz** [comment]
你把你网站发来看看撒

**Comment by zyy24796143** [comment]
https://www.seafog.cn/

**Comment by zyy24796143** [comment]
还有日志的头像，是不是也是博客的头像地址？也没显示出来

![image](https://user-images.githubusercontent.com/25009398/163669138-3d7568b7-319c-4412-8cf4-2b565daee0b2.png)

**Comment by ruibaby** [comment]
这个是在个人资料设置。

<img width="340" alt="image" src="https://user-images.githubusercontent.com/21301288/163680741-09ef6542-6dba-4719-ad22-989a4075a79c.png">

**Comment by zyy24796143** [comment]
好吧，原来我把个人头像跟logo搞混了……
