### ISSUE TITLE
部分CSS和JS文件加载过慢

### ISSUE THREAD

**Issue by limonene0x** [xzhuz/halo-theme-xue#255]
部分CSS和JS文件在低配服务器上加载过慢，能不能改为用CDN加载呀
![Snipaste_2022-04-14_16-48-56](https://user-images.githubusercontent.com/47286271/163349341-008724ed-2749-45b5-b2cf-c86fbf5300ef.png)

**Comment by manction** [comment]
因为 cdn.jsdelivr.net 网络已经出现问题，该主题从**1.3.1**版开始取消使用 jsDelivr CDN 资源，将静态资源文件本地化了，需要自行优化。
**优化案例**
月光海岸：https://www.manction.com

**Comment by wangyu1209** [comment]
> 因为 cdn.jsdelivr.net 网络已经出现问题，该主题从**1.3.1**版开始取消使用 jsDelivr CDN 资源，将静态资源文件本地化了，需要自行优化。 **优化案例** 月光海岸：https://www.manction.com

请教一下，后台替换了评论模块的js后，评论图片不显示问题如何解决，我看调用了cdn.v2ex这个地址的图片

**Comment by xzhuz** [comment]
> > 因为 cdn.jsdelivr.net 网络已经出现问题，该主题从**1.3.1**版开始取消使用 jsDelivr CDN 资源，将静态资源文件本地化了，需要自行优化。 **优化案例** 月光海岸：https://www.manction.com
> 
> 请教一下，后台替换了评论模块的js后，评论图片不显示问题如何解决，我看调用了cdn.v2ex这个地址的图片

评论图片和cdn.v2ex这个地址有什么关系吗？

**Comment by wangyu1209** [comment]
> > > 因为 cdn.jsdelivr.net 网络已经出现问题，该主题从**1.3.1**版开始取消使用 jsDelivr CDN 资源，将静态资源文件本地化了，需要自行优化。 **优化案例** 月光海岸：https://www.manction.com
> > 
> > 
> > 请教一下，后台替换了评论模块的js后，评论图片不显示问题如何解决，我看调用了cdn.v2ex这个地址的图片
> 
> 评论图片和cdn.v2ex这个地址有什么关系吗？

![image](https://user-images.githubusercontent.com/65597529/163598880-ac5dd6a7-8d54-4ddd-baf7-42a1a2e119ff.png)
图像是通过cdn.v2ex这个地址获取的，themes/bao/source/js/plugins/halo-comment.min.js我引用的是这个js文件

**Comment by ruibaby** [comment]
可以尝试在评论设置修改镜像源。如果这个评论组件适配了的话。

<img width="813" alt="image" src="https://user-images.githubusercontent.com/21301288/163680797-86d3e006-a12d-4b48-b40e-7ae4f79e1ca1.png">

在网上找一个国内的 gravatar 镜像源即可。

**Comment by wangyu1209** [comment]
> 

我尝试使用这个方法来更换镜像源，现在使用的halo版本为1.5.2，主题版本是1.4.1，在使用上面配置的评论js后还是出现以上问题，感觉好像是js文件直接写死了cdn.v2ex这个地址，使用官方的评论js可以正常显示

**Comment by ruibaby** [comment]
> > 
> 
> 
> 
> 我尝试使用这个方法来更换镜像源，现在使用的halo版本为1.5.2，主题版本是1.4.1，在使用上面配置的评论js后还是出现以上问题，感觉好像是js文件直接写死了cdn.v2ex这个地址，使用官方的评论js可以正常显示

@xzhuz 可以考虑适配一下。
