### ISSUE TITLE
希望可以增加显示宽度设置

### ISSUE THREAD

**Issue by Doddddz** [xzhuz/halo-theme-xue#257]
老哥，我使用的 4K 分辨率下在文章页面显示面积大概在 30% 左右，左右都有大面积空白，可不可以加个设置宽度让它宽点

**Comment by xzhuz** [comment]
并不建议这样做，网页和客户端不一样的，不同用户的环境显示效果是不同的。可能你的博客，在你自己的电脑上的面积是30%左右，但在其它访问者的电脑上面就是 70%。所以，目前的显示比例也是考虑到大多数的情况，而做出的决定。

**Comment by Doddddz** [comment]
> 并不建议这样做，网页和客户端不一样的，不同用户的环境显示效果是不同的。可能你的博客，在你自己的电脑上的面积是 30% 左右，但在其它访问者的电脑上面就是 70%。所以，目前的显示比例也是考虑到大多数的情况，而做出的决定。

好的好的

**Comment by Doddddz** [comment]
老哥，这个跳动的 bug 帮忙解决一下吧
![image](https://user-images.githubusercontent.com/50560734/163663192-858bdc14-b1ec-43d7-b395-5dcd167c9a32.png)

**Comment by xzhuz** [comment]
你是想他跳还是不想他跳呢？这个是会实时跳的

**Comment by Doddddz** [comment]
> 你是想他跳还是不想他跳呢？这个是会实时跳的

我还以为是 Bug，个人觉得不跳会好看点（有点强迫症 qwq
