### ISSUE TITLE
打开或刷新页面默认画布是深色模式一闪而过

### ISSUE THREAD

**Issue by manction** [xzhuz/halo-theme-xue#262]
版本：1.4.1
网站：月光海岸 https://www.manction.com

描述：发现一个小问题，就是每次打开页面，默认会灰色闪一下（应该是默认夜间模式），一闪而过，刷新页面能感受出来，默认画布是灰色的（夜景模式）。

**Comment by TanYongF** [comment]
是这样的，我在亮色模式下也是会遇到这种状况。可能是夜间模式的逻辑导致的吧？
版本：1.4.1
网站：Tan's Blog  https://tans.fun

**Comment by xzhuz** [comment]
已修复
