### ISSUE TITLE
代码复制-复制的内容将换行都去掉了

### ISSUE THREAD

**Issue by loveferry** [xzhuz/halo-theme-xue#264]
举例：
```bash
hostname
ip addr
cat /sys/class/dmi/id/product_uuid
```

复制出来的效果就是
hostnameip addrcat /sys/class/dmi/id/product_uuid

将所有的换行符都过滤了，内容都在一行了，没法用呀

**Comment by Extrwave** [comment]
你好，最新版本好像并没有修复，是因为我更新的问题嘛
blog.ethreal.cn

**Comment by xzhuz** [comment]
问题已修复
