### ISSUE TITLE
Markdown 代码块的行号与代码重叠

### ISSUE THREAD

**Issue by AnotiaWang** [xzhuz/halo-theme-xue#265]
# 问题描述

特定语言下，Markdown 代码块的行号似乎与文本没有间隔，容易与代码重叠。使用其它语言时，如果横向滑动代码，行号也会重叠。

# 复现步骤

1. 新建一个代码块；
2. 代码语言选择 `tl`（Type Language）
3. 输入一些文本

# 截图

![image](https://user-images.githubusercontent.com/62269186/164666478-ee42f351-9d80-4546-aba1-a5b8002c3d97.png)

![image](https://user-images.githubusercontent.com/62269186/164665339-5dcc1021-a9d3-49c0-bc07-4809563674ca.png)

# 其它信息

主题版本：1.4.1
文章地址：https://blog.anotia.top/archives/difference-between-mtproto-tdlib-and-botapi

**Comment by mustvvvics** [comment]
类似的问题，代码块的行号重叠
![image](https://user-images.githubusercontent.com/75075647/176609229-9f4311a6-a7f0-4530-a713-203a8fe274d4.png)

主题版本：1.4.1 ；Halo版本 1.5.3
文章地址：https://mustvv.com/archives/ptuse

**Comment by xzhuz** [comment]
已修复该问题
