### ISSUE TITLE
图片放大过程中出现白色描边

### ISSUE THREAD

**Issue by deadmau5v** [xzhuz/halo-theme-xue#267]
# 左键图片预览时 放大过程中出现白色描边
![image](https://user-images.githubusercontent.com/88039301/164965118-061248b8-28ef-4d15-aaef-cfee57025a43.png)
# 放大完成后就没了
![image](https://user-images.githubusercontent.com/88039301/164965162-65eadbd7-b9e5-43f2-9010-0210138295c5.png)

**Comment by deadmau5v** [comment]
版本：1.4.2
网站：note.deadmau5v.cool

**Comment by xzhuz** [comment]
问题已修复
