### ISSUE TITLE
设置归档页面每页文章条数不生效

### ISSUE THREAD

**Issue by zyy247796143** [xzhuz/halo-theme-xue#268]
halo版本：1.5.2
主体版本：1.4.1
在 halo 管理后台`博客设置`里的`文章设置`页，设置`归档页面每页文章条数：`不生效。当我设置为9时，归档页里已经有11条，也没换页。

**Comment by xzhuz** [comment]
归档页面没有分页

**Comment by zyy247796143** [comment]
了解，还以为是个bug

**Comment by xzhuz** [comment]
> 了解，还以为是个bug

不是的，因为目前样式做了分页就不会很好看
