### ISSUE TITLE
友链页面头部的头像图片无法加载

### ISSUE THREAD

**Issue by DawnGuoDev** [xzhuz/halo-theme-xue#269]
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/28643623/165009146-3e317943-ca7c-4deb-82e2-c1c05431dc64.png">
友情链接页面头部中的头像，默认加载国外的一个图片链接。

**Comment by deadmau5v** [comment]
应该不是主题问题

**Comment by deadmau5v** [comment]
你F12看一下链接有没有错

**Comment by DawnGuoDev** [comment]
默认加载的是 http://cn.gravatar.com/avatar/fc26f790c11218a1c5e483a00bdc5805?s=256&d=mm 这个图片，但是我已经设置了默认头像图片。假如默认设置的头像图片不等于头部的头像图片，但是我也没找到其他位置可以设置的。

<img width="803" alt="image" src="https://user-images.githubusercontent.com/28643623/165009954-3e9cd0d0-aa69-4a41-b87c-d0b86b4e4099.png">

**Comment by DawnGuoDev** [comment]
找到相关的链接了，已经更改了   #254
