### ISSUE TITLE
markdown 代码块渲染不正常

### ISSUE THREAD

**Issue by zyy247796143** [xzhuz/halo-theme-xue#270]
1.4.1 版本的主题中，markdown 代码块渲染不正常
在博客后台编辑的yaml代码如下：
```yaml
string_1: |
  I am a string_1.
  11111.
string_2: |+
  I am a string_2.
  22222.
string_3: |-
  I am a string_3.
  33333.
```
string_2 和 string_3 前面都是没有空格的。但是渲染出来后，前面都不知道怎么来了个空格，导致格式错了：
![image](https://user-images.githubusercontent.com/23225911/165203610-6311ad78-2411-45e4-b84d-6090d9de270b.png)

试过换其他主题，就不会出现这个问题
![image](https://user-images.githubusercontent.com/23225911/165203741-9fdb163c-6c7c-4daa-ac9f-24e0ca2b13f6.png)

**Comment by xzhuz** [comment]
已修复该问题
