### ISSUE TITLE
关闭搜索框功能建议

### ISSUE THREAD

**Issue by zyy247796143** [xzhuz/halo-theme-xue#271]
主体：1.4.1
### 问题
目前点击搜索按钮，打开搜素框后。除了点上面的导航栏重新进入页面，不知道怎么退出这个搜索框。如果点击搜索框外面的话，会报JS错误，PC版和移动版都有这个问题，截图如下：
![image](https://user-images.githubusercontent.com/23225911/165453402-5beb7d65-de98-44c4-8677-a77e3d20ae6f.png)
![image](https://user-images.githubusercontent.com/23225911/165453701-6f169a5b-78f7-4db1-9da8-201552ed2976.png)

### 建议
能否增加一个功能，点击搜索框外面的地方，就关闭搜索框，并保留当前的页面位置的功能？感觉这样体验交互更友好一点。

**Comment by xzhuz** [comment]
好建议，下个版本优化
