### ISSUE TITLE
烦请看下F12开发者控制台报此类警告是什么原因？

### ISSUE THREAD

**Issue by niujinkai** [xzhuz/halo-theme-xue#274]
烦请看下F12开发者控制台报此类警告是什么原因？
具体如图：![mmexport1651728145343.png](https://user-images.githubusercontent.com/97371434/166867415-d5c94750-d4ec-42b3-9a89-41f3f56a74a2.png)

**Comment by manction** [comment]
确切来说也不是个问题，对网站本身没有什么实质性的影响。这个 sourceMap 是方便调试的东西，从打包后的代码映射到源码，并在前端使用注释声明。解决方法：根据路径找到该文件的地址，然后删除文件最后的 sourceMappingURL 注释即可。

**Comment by niujinkai** [comment]
> 确切来说也不是个问题，对网站本身没有什么实质性的影响。这个 sourceMap 是方便调试的东西，从打包后的代码映射到源码，并在前端使用注释声明。解决方法：根据路径找到该文件的地址，然后删除文件最后的 sourceMappingURL 注释即可。
> 
> 名称：月光海岸 
> 链接：https://www.manction.com 
> 图标：https://www.manction.com/logo.png 
> 描述：用心创造快乐！

好的，感谢😁👍
