### ISSUE TITLE
后台管理页面提示框：正在编译主题

### ISSUE THREAD

**Issue by septasset** [xzhuz/halo-theme-xue#276]
今天登陆后台管理系统以后，很多页面的顶端一直有个提示框提示正在编译主题，但博客页面是可以正常访问的，可以忽略吗或是需要做什么吗？
![image](https://user-images.githubusercontent.com/40650235/167064561-55dfc442-9d5b-4882-94cf-a3fda71946c9.png)

**Comment by xzhuz** [comment]
按理说是不需要做什么的，可以联系一下halo

**Comment by septasset** [comment]
谢谢😀
