### ISSUE TITLE
发布新文章后主页不会显示

### ISSUE THREAD

**Issue by Jaolvv** [xzhuz/halo-theme-xue#277]
如标题，在写好新的文章后点击发布，主页不会显示最新发布的文章；需要点击一下左上角的LOGO才会加载刚刚发布的文章。
![](https://cdn.jsdelivr.net/gh/Jaolvv/All_Images_url@main/img/16518542625442022-05-07_002229.jpg)
![](https://cdn.jsdelivr.net/gh/Jaolvv/All_Images_url@main/img/16518542605432022-05-07_002319.jpg)

**Comment by xzhuz** [comment]
你发布了文章之后，必须要刷新之后才能显示。

**Comment by Jaolvv** [comment]
> 你发布了文章之后，必须要刷新之后才能显示。

解决了，原来是我CDN加速开启了资源缓存30天，关闭缓存就可以了。: )
