### ISSUE TITLE
文章目录问题

### ISSUE THREAD

**Issue by loongzcode** [xzhuz/halo-theme-xue#279]
目录在亮色模式下，目录被选中的状态不明显，在暗色模式下，字体显示不太清楚

**Comment by manction** [comment]
同感 +1

月光海岸 ，用心创造快乐！
https://www.manction.com

**Comment by xzhuz** [comment]
我尝试优化一下

**Comment by yangJiang-create** [comment]
之前废弃的文章目录方案感觉就很棒：https://github.com/xzhuz/xue-touch-circle 
不过一想到要做自动触发，自动退出就头好大。

**Comment by yangJiang-create** [comment]
简单的复现了一下~


> 之前废弃的文章目录方案感觉就很棒：https://github.com/xzhuz/xue-touch-circle 不过一想到要做自动触发，自动退出就头好大。

**Comment by xzhuz** [comment]
已优化该问题
