### ISSUE TITLE
Halo1.5.0: 评论表单中邮箱地址不再作为必填项

### ISSUE THREAD

**Issue by LiumxRyan** [xzhuz/halo-theme-xue#280]
Halo1.5.0更新评论表单中邮箱地址不再作为必填项，但是现在的主题还是要填邮箱才能评论，可以适配下吗

**Comment by xzhuz** [comment]
这个是评论插件的功能，你现在用的是那个评论插件？

**Comment by LiumxRyan** [comment]
这个
https://cdn.jsdelivr.net/gh/hshanx/halo-comment-fly@latest/dist/halo-comment.min.js
