### ISSUE TITLE
1.4.1 版本主题小建议

### ISSUE THREAD

**Issue by zyy247796143** [xzhuz/halo-theme-xue#282]
有4个小问题：
1. 主题设置里的通用设置，“首页文章列表展示风格：” 这一栏文案，修改为“首页文章展示风格：”感觉比较好一些。
2. 用户访问统计功能这里，选择关闭的话，主体是否就会停止统计？停止统计了，如果后期想开回来，好像还是之前关闭的数量。。。看其他主题关闭了这个功能，主题也可以设置继续统计，只是不展示。
3. 首页文章如果是列表形式展示的话，文章的标签列出的是文章分组。卡片形式展示的却是正常的标签（虽然只展示到一个标签）。这里不太统一，不知道是不是bug。
4. 像这种卡片式的布局，如果有一个的标题比较长的话，会导致这一行的卡片都会相应的变长，但是文章的发表日期这些元素就有点不太好看。修改一下日期这些元素此终贴卡片底部会不会比较好？视觉比较一些
![image](https://user-images.githubusercontent.com/23225911/170805334-2c49ebfe-20c9-4f95-85e7-0e7460d8a269.png)

**Comment by xzhuz** [comment]
1. 好建议，多谢
2. 只是不展示
3. 额，我觉得我这个是 bug，多谢。我再确认一下
4. 这个是有点问题的，应该是这样

**Comment by zyy247796143** [comment]
第二个用户访问统计功能这里，刚开始搭建的时候，关闭了一段时间。直到后台的阅读量：1061的时候，重新打开用户统计，发现用户：30、访问：91。相差不是一般的大，所以感觉像关闭了就没有统计。

**Comment by yangJiang-create** [comment]
之前1.3.1版本（我现在的版）的会把长的标题不完全展示，这个不算BUG。

**Comment by xzhuz** [comment]
已修复该问题
