### ISSUE TITLE
友链页面加载不出来

### ISSUE THREAD

**Issue by fumeng521** [xzhuz/halo-theme-xue#283]
不知道是不是版本不兼容的问题，我这的友链页面加载不出来

**Comment by xzhuz** [comment]
麻烦给个链接呢

**Comment by fumeng521** [comment]
101.43.207.243:8090博客地址

宝塔系统
halo版本1.5.0
麻烦您帮忙看下
我的微信fmyule
我的QQ2574482675
真的喜欢这个主题，不舍得改



---- 回复的原邮件 ----
| 发件人 | Xiao ***@***.***> |
| 日期 | 2022年06月12日 20:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [xzhuz/halo-theme-xue] 友链页面加载不出来 (Issue #283) |

麻烦给个链接呢

**Comment by BojackFang** [comment]
> ![image](https://user-images.githubusercontent.com/18698028/178937050-bca2d56e-4b3b-4f83-889c-471c9f675d84.png) 我的也是友链加载有问题，halo版本1,5,4, 主题也是最新的 根据页面抛出的错误定位到 links.ftl 17行，我在源码里找到这一行，估摸着是没有判空，改了下就可以正常访问了，如下图 ![image](https://user-images.githubusercontent.com/18698028/178938030-d8c31ff9-7d51-40c4-a8a8-22af0a6efc04.png) 如果还未解决，我就不清楚其它原因了，最好 F12 看下有没有抛出错误

那里应该是 settings.home_descrition?? ,截图时手误，不是 item.xxxxx

**Comment by xzhuz** [comment]
> > ![image](https://user-images.githubusercontent.com/18698028/178937050-bca2d56e-4b3b-4f83-889c-471c9f675d84.png) 我的也是友链加载有问题，halo版本1,5,4, 主题也是最新的 根据页面抛出的错误定位到 links.ftl 17行，我在源码里找到这一行，估摸着是没有判空，改了下就可以正常访问了，如下图 ![image](https://user-images.githubusercontent.com/18698028/178938030-d8c31ff9-7d51-40c4-a8a8-22af0a6efc04.png) 如果还未解决，我就不清楚其它原因了，最好 F12 看下有没有抛出错误
> 
> 那里应该是 settings.home_descrition?? ,截图时手误，不是 item.xxxxx

不是 Item.xx ，解决问题了吗？

**Comment by xzhuz** [comment]
https://github.com/xzhuz/halo-theme-xue/releases/tag/1.4.3
