### ISSUE TITLE
页面代码块显示问题

### ISSUE THREAD

**Issue by yikexiaoyao** [xzhuz/halo-theme-xue#285]
连续两个代码块在页面中默认连接略微重叠，建议增加间隔

**Comment by xzhuz** [comment]
麻烦给个链接呢

**Comment by yikexiaoyao** [comment]
![Snipaste_2022-06-12_19-31-31](https://user-images.githubusercontent.com/36374114/173234396-a6a913b2-61b0-43d2-bb6a-61f79ef053b2.png)

**Comment by yikexiaoyao** [comment]
https://www.tingyuxuan.tk/archives/%E6%8F%92%E4%BB%B6%E5%BC%8F%E5%BC%80%E5%8F%91quartz%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1

**Comment by xzhuz** [comment]
已修复
