### ISSUE TITLE
文章标签显示问题

### ISSUE THREAD

**Issue by yikexiaoyao** [xzhuz/halo-theme-xue#286]
![Snipaste_2022-06-20_14-26-47](https://user-images.githubusercontent.com/36374114/174538964-6b60d149-248e-428b-90f3-6954499f873e.png)
![Snipaste_2022-06-20_14-27-00](https://user-images.githubusercontent.com/36374114/174538990-1146dafa-c4ba-4a81-bccf-dd80bd12f73a.png)
文章设置了多个标签，但是在首页缩略图显示的时候只显示第一个标签，文章页面最后却能显示全部标签，请问是因为设置问题还是原本设计就这样，如果是设计导致请问能改一下吗，谢谢

**Comment by yikexiaoyao** [comment]
提个建议，首页缩略图可以不用显示全部标签，以防用户设置标签过多导致卡片内容拥挤不协调，可以设计成，总标签数三个以内，首页文章卡片上显示全部标签，总标签数三个以上，首页文章卡片上只显示前三个标签，其余用省略号代替或者直接不显示，点开文章页面后可显示全部标签，个人建议，望采纳O(∩_∩)O~~

**Comment by xzhuz** [comment]
是一个好建议

**Comment by xzhuz** [comment]
已升级
