### ISSUE TITLE
友链页面样式有问题

### ISSUE THREAD

**Issue by liutingfenga** [xzhuz/halo-theme-xue#287]
![A4BB3FF6-25AA-44F7-B7A3-6B0A7FDAC32F-1655993644578](/upload/2022/06/A4BB3FF6-25AA-44F7-B7A3-6B0A7FDAC32F-1655993644578.png)

地址：https://86s.cc

**Comment by liutingfenga** [comment]
[https://86s.cc/upload/2022/06/A4BB3FF6-25AA-44F7-B7A3-6B0A7FDAC32F-1655993644578.png](url)

**Comment by liutingfenga** [comment]
你好 友情链接页面没有评论

**Comment by manction** [comment]
> 你好 友情链接页面没有评论

在Halo后台-页面-新建页面-发布-高级-选择 links 自定义模板，这样友情链接页面就有评论了。
可以参考我的案例：https://www.manction.com/s/links

**Comment by xzhuz** [comment]
@manction 楼上正解

**Comment by sunerpy** [comment]
> > 你好 友情链接页面没有评论
> 
> 在Halo后台-页面-新建页面-发布-高级-选择 links 自定义模板，这样友情链接页面就有评论了。 可以参考我的案例：https://www.manction.com/s/links

你好，请教下这种发布的页面虽然可以评论了，但是links链接没显示在页面里了
