### ISSUE TITLE
文章侧边目录不显示

### ISSUE THREAD

**Issue by zhiqiuyuan** [xzhuz/halo-theme-xue#292]
文章目录功能请问还支持嘛？设置文章目录开启与关闭、夜间或白天模式，文章都不会显示侧边目录呢？

**Comment by zhiqiuyuan** [comment]
有一个折中的方法（给后面使用此主题的小伙伴们）：在markdown文档顶部添加[TOC]，然后会在文章首部出现目录，虽然没有侧边目录方便，但是比没有目录方便~

**Comment by yangJiang-create** [comment]
这个方案你看可以吗？https://www.jiangmiemie.com/

**Comment by yangJiang-create** [comment]
> 

这个方案你看可以吗？https://www.jiangmiemie.com/

**Comment by zhiqiuyuan** [comment]
> 

谢谢！有侧边目录了！我学习下
如果侧边目录可以在切换夜间模式之后也换成dark mode就更好啦

**Comment by yangJiang-create** [comment]
你仔细观察字体颜色是有改变的，你应该要的是CSS大改

**Comment by yangJiang-create** [comment]
我修改了下，你看是不是你要的效果

**Comment by zhiqiuyuan** [comment]
谢谢！意思大概是这样
不过我想侧边目录切换成dark mode之后是不是目录文字变成浅色比较好hh这样看得清楚一些😀谢谢！

**Comment by yangJiang-create** [comment]
代码放在这里啦![image](https://user-images.githubusercontent.com/69161207/178419386-ebb2de8f-077b-4079-90ba-378cd37b14ac.png)

**Comment by zhiqiuyuan** [comment]
嗯嗯谢谢！
