### ISSUE TITLE
分享链接功能当中，只包含了路径部分，未包含域名部分，希望修复~

### ISSUE THREAD

**Issue by niujinkai** [xzhuz/halo-theme-xue#298]
分享链接功能当中，只包含了路径部分，未包含域名部分，希望修复~
![image](https://user-images.githubusercontent.com/97371434/187041855-0e4667ee-8894-48dc-bad7-a917130b5674.png)
![image](https://user-images.githubusercontent.com/97371434/187041859-98853acc-2b96-4269-88bd-112d86bdd547.png)

**Comment by xzhuz** [comment]
最新 halo 分支已修复该分支

**Comment by niujinkai** [comment]
还是存在 测试未修复

**Comment by manction** [comment]
这个问题，只要在Halo后台-系统-博客设置-切换到高级选项-其他设置，打开**全局绝对路径**开关即可解决。

查看同款主题案例：https://www.manction.com
