### ISSUE TITLE
代码块较长时，字距异常

### ISSUE THREAD

**Issue by AnotiaWang** [xzhuz/halo-theme-xue#301]
在代码块比较长的时候，单行的字距会变得很大

![image](https://user-images.githubusercontent.com/62269186/187062881-50446fc4-4a2e-4ba3-aa5a-e1f6fc33e539.png)

示例链接：https://blog.ataw.top/archives/gi-cutscenes-tutorial

**Comment by xzhuz** [comment]
最新 halo 分支已修复该问题
