### ISSUE TITLE
部分元素不会被导航栏遮挡

### ISSUE THREAD

**Issue by AnotiaWang** [xzhuz/halo-theme-xue#302]
找到了三处元素：

- 博客首页的文章标题：

![image](https://user-images.githubusercontent.com/62269186/187063258-9cfec1ce-8380-46bc-ae15-31a241f3f77d.png)

- 文章详情页的小标题（仅深色模式下存在此问题）：

![image](https://user-images.githubusercontent.com/62269186/187063135-ab7228a2-0024-42d5-aa14-4623f029e59d.png)

- 文章详情页的打赏按钮：

![image](https://user-images.githubusercontent.com/62269186/187063166-2bd09550-3042-4595-9b16-c699f00cdce9.png)
![image](https://user-images.githubusercontent.com/62269186/187063168-f60dc110-a1a0-4bda-9bb6-1612831ff99c.png)

**Comment by xzhuz** [comment]
最新 halo 分支已修复该问题
