### ISSUE TITLE
JS 苦手，请问如何调整文章页面宽度

### ISSUE THREAD

**Issue by ydeng11** [xzhuz/halo-theme-xue#307]
现在感觉页面有点儿窄，想问在哪里调整？
谢谢

**Comment by wanyoou** [comment]
我也在找，感觉文章页面再宽点就好了

**Comment by manction** [comment]
如果想改文章页的宽度，也是可以的，在Halo后台-外观-主题编辑，找到 post.ftl 文件，搜索 max-w-4xl 字符串，替换为 max-w-5xl ，这样页面就更宽了，如果想全屏，则替换为 max-w-full 

示例网站：https://www.manction.com

**Comment by ydeng11** [comment]
太感谢了！
