### ISSUE TITLE
1.5.4halo对应最新1.4.2xue主题，友情链接页面报错

### ISSUE THREAD

**Issue by duramisu** [xzhuz/halo-theme-xue#310]
1.5.4halo对应最新1.4.2xue主题，友情链接页面报错，错误参考：https://xhsblog.cn/links

**Comment by ruibaby** [comment]
duplicate https://github.com/xzhuz/halo-theme-xue/issues/283

**Comment by duramisu** [comment]
临时解决方案：
修改links.ftl中的：
<#if settings.home_description!=''>
  <p class="slogan text-center text-white dark:text-gray-300 text-lg md:text-xl text-center">
    ${settings.home_description!}
  </p>
</#if>
替换为：
<p class="slogan text-center text-white dark:text-gray-300 text-lg md:text-xl text-center">
           伙伴(或者你想要的名字)
 </p>

**Comment by xzhuz** [comment]
后期修改

**Comment by xzhuz** [comment]
https://github.com/xzhuz/halo-theme-xue/releases/tag/1.4.3
