### ISSUE TITLE
修改comment组件没有作用

### ISSUE THREAD

**Issue by ydeng11** [xzhuz/halo-theme-xue#311]
在后台修改comment组件后，没有变化。
修改为了https://github.com/halo-dev/halo-comment-yu
但是还是使用的halo-comment-normal的组件。
重新加载主题也没变化。
在demo站测试过了，这个主题无法改变评论组件。
请问如何才能使用其它组件？
谢谢

**Comment by xzhuz** [comment]
估计是代码里面写死了，是个 bug，下个版本修复下

**Comment by ydeng11** [comment]
谢谢
