### ISSUE TITLE
适配 Halo 2.0

### ISSUE THREAD

**Issue by ruibaby** [xzhuz/halo-theme-xue#312]
目前 Halo 2.0 即将发布 alpha 版本，可以考虑将本主题适配到 2.0 了。

@xzhuz 是否可以新建一个 next 分支，我可以尝试完成这项工作。

**Comment by ColanCN** [comment]
这个可以有，超喜欢xun这个主题。如果能适配就谢谢各位开发大大了！😄

**Comment by ruibaby** [comment]
> 这个可以有，超喜欢xun这个主题。如果能适配就谢谢各位开发大大了！😄

已经完成大部分适配了：https://github.com/xzhuz/halo-theme-xue/tree/next

**Comment by KamToHung** [comment]
你好，通过迁移工具导入的文章没有按照时间顺序展示···请问下如何解决

**Comment by rjszz** [comment]
> > 这个可以有，超喜欢xun这个主题。如果能适配就谢谢各位开发大大了！😄
> 
> 已经完成大部分适配了：https://github.com/xzhuz/halo-theme-xue/tree/next

大佬可不可以开发一下默认配色呀，现在是默认深色，我个人还是更喜欢浅色，但是设置不了
