### ISSUE TITLE
jQuery依赖存在漏洞

### ISSUE THREAD

**Issue by BenanaH** [xzhuz/halo-theme-xue#313]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/43538540/193490782-32b0ed20-6be5-4c5a-9ef1-79bc800932b2.png">

> jQuery版本:3.2.1
> 升级到官网最新版本:3.6.1

**Comment by xzhuz** [comment]
谢谢提醒，尽快发布新版本修复

**Comment by xzhuz** [comment]
https://github.com/xzhuz/halo-theme-xue/releases/tag/1.4.3
