### ISSUE TITLE
主题xue当前版本1.4.2是否不适应最新版的halo1.5.4

### ISSUE THREAD

**Issue by govbk** [xzhuz/halo-theme-xue#314]
主题xue当前版本1.4.2是否不适应最新版的halo1.5.2，在线更新至1.4.2后就显示这种情况
![image](https://user-images.githubusercontent.com/21957825/194002444-e5178f58-bfb8-47e5-ac00-acf45af22ddf.png)

**Comment by govbk** [comment]
每个版本都试了，换到原来的1.3.1版本又没有问题了，我的是docker搭建的。
![image](https://user-images.githubusercontent.com/21957825/194005187-0ac01d37-f707-4976-b673-70a7a69ad38e.png)
![image](https://user-images.githubusercontent.com/21957825/194005224-2db33d94-5ef6-434b-8467-495d8d7ee44e.png)

**Comment by xzhuz** [comment]
<img width="728" alt="image" src="https://user-images.githubusercontent.com/23736683/194363963-c17d786b-8113-4d1f-bf58-61d9eef5413e.png">
我也是用的最新版本的，是没有问题的，你看下是不是缓存的问题呢？

**Comment by govbk** [comment]
找到问题原因了，我博客用的是cdn，源站点不是绑定的域名，在后台博客设置那设置成cdn的域名就会显示出错，我重新搭建了一套设置成服务器的IP就行，这个问题能解决吗，还是得舍弃cdn
![image](https://user-images.githubusercontent.com/21957825/194683122-f0b0bcc2-2064-4db3-8b4b-2ae86ec6101f.png)

**Comment by xzhuz** [comment]
好的
