### ISSUE TITLE
网站slogan设置为Null导致友情链接页面报错

### ISSUE THREAD

**Issue by oyxy2019** [xzhuz/halo-theme-xue#319]
在halo后台，将【主题设置】->【首页设置】->【网站slogan：】内容清空，这会导致“友情链接“页面报错（如图）
![image](https://user-images.githubusercontent.com/53966815/199466468-7f430d0c-7cd6-4f14-818f-43b0fb94c77f.png)

错误信息：
`FreeMarker template error (DEBUG mode; use RETHROW in production!): The following has evaluated to null or missing: ==> **settings.home_description [in template "themes/bao/links.ftl" at line 17, column 14]** ---- Tip: It's the step after the last dot that caused this error, not those before it. ---- Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ...`

已解决：
在【网站slogan：（用于网页描述）】中随便加点文字

**Comment by xzhuz** [comment]
https://github.com/xzhuz/halo-theme-xue/releases/tag/1.4.3
