### ISSUE TITLE
请问可否添加WebApp全屏模式，谢谢。

### ISSUE THREAD

**Issue by ZHU-SK** [xzhuz/halo-theme-xue#322]
我查到需要添加这段代码，但请问这段代码需要插在哪里呢？我是小白，第一次学习，谢谢您的解答。

`
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-touch-fullscreen" content="yes" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" name="viewport" />`

**Comment by manction** [comment]
如果你想自定义话，代码可以插入这个位置：
Halo后台-外观-主题编辑-module-macro.ftl 第10行

月光海岸
https://www.manction.com

**Comment by ZHU-SK** [comment]
谢谢您的指导，再次感谢。
