### ISSUE TITLE
关于Photos页面的深色模式

### ISSUE THREAD

**Issue by ZHU-SK** [xzhuz/halo-theme-xue#326]
作者您好，

因为Photo页面展示的都是图片，但是黑色模式下会给整个页面都加一层灰色遮罩，导致图片色彩失真，如同加了一层降低亮度的滤镜；请问可不可以让图片部分保持自身色彩呢？

谢谢

**Comment by xzhuz** [comment]
这种主要是了降低图片亮度，避免在深色模式下某些图片有刺眼的效果

**Comment by ZHU-SK** [comment]
> 这种主要是了降低图片亮度，避免在深色模式下某些图片有刺眼的效果

谢谢你，因为主页面深色模式没有削减封面亮度，所以我以为是自己设置的问题。谢谢你了。
