### ISSUE TITLE
Halo 2.x Next分支中点赞功能失效。

### ISSUE THREAD

**Issue by ZHU-SK** [xzhuz/halo-theme-xue#335]
作者您好，我很喜欢您的主题，最近升级了halo 2.x，发现文章发布页的红心点赞功能失效，请问需要怎样修改一下呢？谢谢。

示例：https://iceky.eu.org/archives/hello-halo

**Comment by ZHU-SK** [comment]
之前1.6的时候使用没问题的。升级之后就无法点赞了。谢谢。

**Comment by xzhuz** [comment]
目前某些功能还未完全支持 2.0，待后续更新

**Comment by ruibaby** [comment]
已经在 https://github.com/xzhuz/halo-theme-xue/commit/89423f2cd43e213c232127afbcae2814c659e2e2 中支持。
