### ISSUE TITLE
主题无法安装

### ISSUE THREAD

**Issue by padoru233** [xzhuz/halo-theme-xue#337]
2.1.0仪表盘安装主题失败
> Internal Server Error: The [theme.yaml] does not conform to the theme specification.

**Comment by padoru233** [comment]
好像是还没做移植？
太喜欢这个主题了，再等等

**Comment by tellbin** [comment]
> next分支是可用的
1. `git clone -b next https://github.com/xzhuz/halo-theme-xue.git halo-theme-xue-next`
2. 压缩目录
4. 导入主题

**Comment by xzhuz** [comment]
三楼同学说的对
