### ISSUE TITLE
2.0beta1. 建站日期bug

### ISSUE THREAD

**Issue by CnDaiL** [xzhuz/halo-theme-xue#342]
如果不填写建站日期，右下角没有显示
当我们第一次填写建站日期，在首页刷新后，右下角出现了建站日期
然后在后台，删除掉建站日期，保存，首页刷新，右下角的日期变成了, NA 年 NA月 NA  啥啥的

主题设置，文章页面，支付宝 微信 二维码一样， 不设置不显示，设置了以后，在删除保存，在前台，不会同步删除

**Comment by ruibaby** [comment]
Close in https://github.com/xzhuz/halo-theme-xue/commit/e6259c40aab21e45069a8f1a1d7265c8d43c2cbf
