### ISSUE TITLE
冰天雪地求2.0beta1更新 适配瞬间和图库插件

### ISSUE THREAD

**Issue by CnDaiL** [xzhuz/halo-theme-xue#345]
[plugin-moments](https://github.com/halo-sigs/plugin-moments) - Halo 2.0 的瞬间管理插件
[plugin-photos](https://github.com/halo-sigs/plugin-photos) - Halo 2.0 的图库管理插件

我自己在1panel下的模板文件里建立个这俩 页面，但是看不懂适配的代码

请求适配啊~~~~

**Comment by ruibaby** [comment]
已经在 https://github.com/xzhuz/halo-theme-xue/pull/346 中支持，但还未发布版本。暂时你可以通过直接下载 next 分支 zip 的方式安装。
