### ISSUE TITLE
关于next分支的相册和文章页

### ISSUE THREAD

**Issue by sunerpy** [xzhuz/halo-theme-xue#347]
1.next分支没有相册页面和功能么，我在页面里只看到一个关于页面
2.文章内容页，能否在侧栏加上文章列表呢，类似于下图
![image](https://github.com/xzhuz/halo-theme-xue/assets/30691040/aefea6bc-4cee-437c-a74b-0b5c657a4703)

**Comment by ruibaby** [comment]
1. 在 next 分支已经提供了 photos.html 的模板：<https://github.com/xzhuz/halo-theme-xue/blob/next/templates/photos.html>，你需要安装 https://github.com/halo-sigs/plugin-photos 插件，然后访问 /photos
2. 目前的设计布局似乎不太方便这样做，不过可以考虑在文章底部添加推荐文章。
