### ISSUE TITLE
请教下关于模板的问题

### ISSUE THREAD

**Issue by sunerpy** [xzhuz/halo-theme-xue#349]
我想发布一个友链页面，我看template里面是有links.html的，但是在发布页面的时候只有一个默认模板，这个具体要怎么才能使用到友链模板呢

![image](https://github.com/xzhuz/halo-theme-xue/assets/30691040/f630d507-8eea-4a0a-8b92-ed6e3c9b5b64)

**Comment by ruibaby** [comment]
安装链接插件之后直接访问 /links 即可。

https://github.com/halo-sigs/plugin-links

**Comment by sunerpy** [comment]
> 安装链接插件之后直接访问 /links 即可。
> 
> https://github.com/halo-sigs/plugin-links


这样子进去的links页面是空的，有能编辑页面的地方么
