### ISSUE TITLE
next分支首页不更新文章浏览次数等统计信息

### ISSUE THREAD

**Issue by sunerpy** [xzhuz/halo-theme-xue#350]
这个图是首页显示的统计信息
![image](https://github.com/xzhuz/halo-theme-xue/assets/30691040/7bd5ebd3-f79d-4e20-8368-c8aba375b11a)

这个图是点进文章后显示的统计信息
![image](https://github.com/xzhuz/halo-theme-xue/assets/30691040/4edb4b5d-25eb-4a9a-ab83-26cdc95b51e5)

**Comment by ruibaby** [comment]
已经在 https://github.com/xzhuz/halo-theme-xue/commit/04ef33452533c56773138422726ee5e59fe1f20e 中修复。
