### ISSUE TITLE
请问如何将首页背景更换为视频？

### ISSUE THREAD

**Issue by Vulcan-W** [xzhuz/halo-theme-xue#351]
请问如何将首页背景更换为视频？
guys, how to replace the background pic with video?

**Comment by manction** [comment]
通过自定义主题的 index.ftl 首页模板解决，效果案例：
[https://www.manction.com](https://www.manction.com)

**Comment by Vulcan-W** [comment]
> 通过自定义主题的 index.ftl 首页模板解决，效果案例： https://www.manction.com

多谢大佬
