### ISSUE TITLE
瞬间前台不显示图片

### ISSUE THREAD

**Issue by loongzcode** [xzhuz/halo-theme-xue#353]
希望能够增加图片的显示

**Comment by loongzcode** [comment]
还有我的搜索没效果

**Comment by PulSe-kun** [comment]
> 希望能够增加图片的显示

需要选择后再拖选
![image](https://github.com/xzhuz/halo-theme-xue/assets/66857592/481e1b7b-7e3d-4165-a722-6c9af1443985)

**Comment by ruibaby** [comment]
已经在 https://github.com/xzhuz/halo-theme-xue/commit/a16c1a209b4e1593572b189adb527559052bcdfa 中支持，稍后我会发布一个版本。
