### ISSUE TITLE
halo2.9 首页文章卡片不显示访问数据与摘要

### ISSUE THREAD

**Issue by Yzzzed** [xzhuz/halo-theme-xue#358]
文章都是从halo1.6迁移过来的 后台数据显示正常
![image](https://github.com/xzhuz/halo-theme-xue/assets/43776976/498cf199-587c-4801-b1f6-6c770ae980ac)
![image](https://github.com/xzhuz/halo-theme-xue/assets/43776976/bf08ec71-fa77-431c-88fc-63a66d45ccfe)

**Comment by ruibaby** [comment]
应该已经在 https://github.com/xzhuz/halo-theme-xue/commit/04ef33452533c56773138422726ee5e59fe1f20e 中修复，稍后我会创建一个 release。
