### ISSUE TITLE
Halo 2.x 一直默认深夜模式

### ISSUE THREAD

**Issue by ZHU-SK** [xzhuz/halo-theme-xue#359]
换了很多浏览器，一直都是默认黑夜模式，请问可以强制白天模式么？或者请问怎么处理这个情况呢？谢谢作者。

**Comment by ZHU-SK** [comment]
网站：iceky.eu.org
也是用的最新的Xue主题。多谢。

**Comment by uluckystar** [comment]
求解决

**Comment by ruibaby** [comment]
已经在 https://github.com/xzhuz/halo-theme-xue/commit/8fab27fdbc5e9d697d045fb61d07f215d649245f 中修复，稍后我会发布一个 Release。
