### ISSUE TITLE
公告：下个版本计划去掉二级菜单了！！！！

### ISSUE THREAD

**Issue by xzhuz** [xzhuz/halo-theme-xue#59]
实在抱歉。由于自己能力有限，目前二级菜单的问题很多，且无法修改。也为了主题的稳定性，计划在下个版本的时候，去掉二级菜单！！！
我也浏览了许多优秀网站的二级的菜单，要不是不符合当前主题要不就是不怎么满意，且自己也没有很好的想法来做这个二级菜单。所以就去掉了，实在抱歉。
如果有能力和想法的同学，可以在下个版本的时候，对主题进行修改和pr，谢谢各位的支持。

**Comment by QianXun0827** [comment]
二级菜单重度依赖户哭晕在厕所

**Comment by xzzai** [comment]
> 二级菜单重度依赖户哭晕在厕所

主要是本主题的二级主题问题太多，也没有找到好的技术方案，所以就计划暂时不支持了。

**Comment by congjinruo** [comment]
很喜欢这个主题，巨赞，我尝试了halo下面的绝大部分主题，个人最喜欢这个。就是最新版有几个小建议。  
1. PC端下打开的时候能不能不折叠顶部菜单，感觉要点两次或者下滑才能切换菜单；  
2. 还有就是底部右下角小工具栏关闭的时候，能不能把搜索按钮还原到顶部菜单上面；  
3. 热门文章区域，普通文章区域，是否考虑置顶文章区域？或者说加一个设置，让置顶文章替代热门文章？毕竟置顶文章可以自己设置，热门文章不行。  
就算是现在这个版本，也趋近于完美了，点赞。

**Comment by xzzai** [comment]
> 很喜欢这个主题，巨赞，我尝试了halo下面的绝大部分主题，个人最喜欢这个。就是最新版有几个小建议。
> 
> 1. PC端下打开的时候能不能不折叠顶部菜单，感觉要点两次或者下滑才能切换菜单；
> 2. 还有就是底部右下角小工具栏关闭的时候，能不能把搜索按钮还原到顶部菜单上面；
> 3. 热门文章区域，普通文章区域，是否考虑置顶文章区域？或者说加一个设置，让置顶文章替代热门文章？毕竟置顶文章可以自己设置，热门文章不行。
>    就算是现在这个版本，也趋近于完美了，点赞。

1. 这个交互后面可以，应该只需要点一次就可以出现菜单。不展开主要是为了考虑首页图片全屏的情况
2. 这个建议确实可以。
3. 变成置顶文章也是可以的，在后面的版本加上试试
