### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by codesensi** [xzhuz/halo-theme-xue#81]
现用 halo-theme-xue_hotfix_2.zip 版本
1：博客运行时间没有实时变化；
2：相册无法加载；
3：个人感觉分类页面应该和标签页面做出区别，我是直接还原到以前版本的样式了；
（演示地址：https://codesensi.top/categories）
代码放不上来。。。。。。。。
4：当页面一屏能显示时，菜单栏不会默认展开。
PS：暂时就这些，大佬万安，哈哈哈哈哈

**Comment by xzzai** [comment]
你不用这个版本，你用1.2.2 的 halo-theme-xue_1.2.3_beta.4.zip 相册是没有问题的

**Comment by xzhuz** [comment]
您好，感谢你宝贵的建议。
1. 博客运行时间实时变化会造成下面的bagde会闪现，体验不是很好，所以去掉了。
2. 最新的master分支修复了相册问题。且最新版本的相册需要在管理后台=>主题设置=>高级功能中打开启用相册开关
3. 关于标签和分类页面，个人感觉两个功能差不多，页面效果一样没有什么问题。
4. 我在最新master代码中新加了是否隐藏菜单的开关，你可以拉取最新master分支代码尝试修复。
如果你要安装最新的代码，您可以拉取最新的分支也可以从1.2.2的tag中下载 halo-theme-xue_1.2.3_beta.5.zip文件进行离线安装。
