### ISSUE TITLE
代码高亮的颜色显示都太浅了

### ISSUE THREAD

**Issue by heya0** [xzhuz/halo-theme-xue#83]
主题里面自带的几种代码高亮风格，颜色都太浅了，我手工加了几种风格，比如Solarizd，但完全没高亮颜色。

请问能否把代码高亮风格颜色提亮一点？有助于显示代码里面的关键字。

另外行内代码（非代码块）现在默认的是灰色，请问如果我要改成红色，应该在哪里改呢？😄😄

**Comment by zhixiangyuan** [comment]
[修改 halo-theme-xue 代码背景颜色](http://xiangbei.life/2020/10/16/xiu-gai--h-a-l-o---t-h-e-m-e---x-u-e--dai-ma-bei-jing-yan-se)

你可以先用我这个方法临时修改一下

**Comment by xzhuz** [comment]
突然看到一个博客http://xiangbei.life/2020/10/16/xiu-gai--h-a-l-o---t-h-e-m-e---x-u-e--dai-ma-bei-jing-yan-se

**Comment by heya0** [comment]
@zhixiangyuan @xzhuz 我看其他人用这个方法可以修改，我按这个方法修改了颜色并没有生效，甚至我直接删除了dist/style.min.css这个文件，网页一样显示正常。
请问是哪里的问题呢？

**Comment by heya0** [comment]
是缓存问题，可以改颜色
