### ISSUE TITLE
随机图片希望能不出现重复的图片

### ISSUE THREAD

**Issue by zhixiangyuan** [xzhuz/halo-theme-xue#84]
现象：首页随机图片会出现重复图片
期望：随机到的图片不重复

![image](https://user-images.githubusercontent.com/25138766/96205730-e6b58200-0f99-11eb-8517-7fe04e72ce70.png)

我在后台配置了十几张图片，但是随机图片的时候图片会重复

![image](https://user-images.githubusercontent.com/25138766/96205762-f765f800-0f99-11eb-9e4e-9a3ee0d3d715.png)

**Comment by xzhuz** [comment]
您好，感谢你提出这个建议。针对你的建议，我在最新master代码上优化了随机图片的算法，但是也不能避免重复图片的出现，只能尽量减少重复的次数。
如果你要安装最新的代码，您可以拉取最新的分支也可以从1.2.2的tag中下载 halo-theme-xue_1.2.3_beta.5.zip文件进行离线安装。
