### ISSUE TITLE
对于代码颜色的疑惑

### ISSUE THREAD

**Issue by zhixiangyuan** [xzhuz/halo-theme-xue#86]
大佬，代码颜色为什么看上去总感觉蒙了一层雾，颜色很淡，这是特意加上去的效果么，如果是的话能否加个开关控制是否开启。

这是目前主体展示出来的效果

![image](https://user-images.githubusercontent.com/25138766/96208996-3c415d00-0fa1-11eb-9f1f-7eef3408e36d.png)

这是别的主题展示出来的效果

![image](https://user-images.githubusercontent.com/25138766/96208957-2e8bd780-0fa1-11eb-892d-959b5954ac07.png)

**Comment by xzhuz** [comment]
你好，你可以F12看下这个背景，然后在管理后台添加自定义背景颜色，这块不计划做成一个功能。

**Comment by zhixiangyuan** [comment]
> 你好，你可以 F12 看下这个背景，然后在管理后台添加自定义背景颜色，这块不计划做成一个功能。

大佬，你说的管理后台添加自定义背景颜色在哪儿设置？

我暂时通过下面这个方式达到了同样的效果，但是这样修改的话下次更新主题就又会回归原状。

[修改 halo-theme-xue 代码背景颜色](http://xiangbei.life/2020/10/16/xiu-gai--h-a-l-o---t-h-e-m-e---x-u-e--dai-ma-bei-jing-yan-se)

**Comment by xzhuz** [comment]
![](https://user-images.githubusercontent.com/23736683/96145468-cf45ad00-0f37-11eb-91c8-a6cf1e3e3405.png)
这个可以自定义样式。
关于字体的话，如果你需要外部字体，可能就需要单独引入。不然的话，也可以在上图指定的地方设置
