### ISSUE TITLE
顶部导航栏建议

### ISSUE THREAD

**Issue by zhixiangyuan** [xzhuz/halo-theme-xue#87]
这个顶部导航栏默认是处于三个横线的样式，需要点击才能展开，这里能不能加个开关控制一下，让其可以默认处于展开状态，不然每次都要将其点挺麻烦的

![image](https://user-images.githubusercontent.com/25138766/96209219-a9ed8900-0fa1-11eb-916d-cf0ad772d502.png)

**Comment by xzhuz** [comment]
感觉您宝贵的建议，针对的你建议，我在最新的master分支代码新加这个功能，你可以拉取最新的分支也可以从1.2.2的tag中下载 halo-theme-xue_1.2.3_beta.5.zip文件进行离线安装。
