### ISSUE TITLE
站点运行时间失效啦

### ISSUE THREAD

**Issue by Jox2018** [xzhuz/halo-theme-xue#88]
站点运行时间失效啦

**Comment by xzhuz** [comment]
你好，关于这个问题的具体表现的怎么样的呢？

**Comment by Jox2018** [comment]
我在后台设置了运行时间（格式正确），前台显示异常（没有显示）
图1和图2是我的设置，图三是示例站点中的千与千寻博客也有这个问题https://blog.chihiro.org.cn/，所以不知道问题出在哪里
![1](https://user-images.githubusercontent.com/44835059/96326815-99ebad00-1066-11eb-9c5a-bf9f011e83dd.png)
![2](https://user-images.githubusercontent.com/44835059/96326817-9eb06100-1066-11eb-9cd1-9a20994e9836.png)
![3](https://user-images.githubusercontent.com/44835059/96326818-a243e800-1066-11eb-88f8-c072d5dba4e7.png)

**Comment by xzhuz** [comment]
你用的是什么版本的呢？
