### ISSUE TITLE
最新版本博文中emoji表情失效了

### ISSUE THREAD

**Issue by y836097668** [xzhuz/halo-theme-xue#91]
比如正文中的 :star: 这样的emoji表情，不会显示了，显示成了``:star:``，求助~

使用的是最新的master分支版本

**Comment by xzhuz** [comment]
不好意思，一直没有看到这个issue。我后面看下，最近没有时间修复这些问题。

**Comment by xzhuz** [comment]
不好意思，这个本主题功能暂时还不支持
