### ISSUE TITLE
文章目录锚点定位 Bug

### ISSUE THREAD

**Issue by zze326** [xzhuz/halo-theme-xue#92]
文章目录如果前几个字符相同，点击后面的目录项只会跳转到第一个。

**Comment by xzhuz** [comment]
你的意思是，有几个目录名字相同？然后点击跳转到第一个了吗？

**Comment by zze326** [comment]
> 你的意思是，有几个目录名字相同？然后点击跳转到第一个了吗？

是的，点击后面的会跳到第一个，不完全相同，可能只是前面两个字相同

**Comment by xzhuz** [comment]
> > 你的意思是，有几个目录名字相同？然后点击跳转到第一个了吗？
> 
> 是的，点击后面的会跳到第一个，不完全相同，可能只是前面两个字相同

理解了，后面会做修复
