### ISSUE TITLE
菜单目录层级配置不生效

### ISSUE THREAD

**Issue by zhixiangyuan** [xzhuz/halo-theme-xue#93]
以下是在后台配置的菜单效果，但是在前台看的时候没有生效，大佬看下怎么展示比较合适

![image](https://user-images.githubusercontent.com/25138766/97071001-81076c80-160f-11eb-9a73-86d578cc1c9d.png)

![image](https://user-images.githubusercontent.com/25138766/97071009-8c5a9800-160f-11eb-907a-da51b3a818e0.png)

以下是我博客地址，（我又无耻的从大佬博客盗了点图😂）

http://xiangbei.life/

**Comment by xzhuz** [comment]
你好，不好意思。目前1.2.x版本不支持二级目录哟。

**Comment by zhixiangyuan** [comment]
> 你好，不好意思。目前 1.2.x 版本不支持二级目录哟。

**Comment by xzhuz** [comment]
> > 你好，不好意思。目前 1.2.x 版本不支持二级目录哟。

后面如果有好的想法，我也会加上
