### ISSUE TITLE
代码渲染的奇怪问题

### ISSUE THREAD

**Issue by 1205747671** [xzhuz/halo-theme-xue#94]
## 我的环境

---
版本：1.4.1
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

## 当前行为
后台：
![image](https://user-images.githubusercontent.com/38599758/97250658-64527b00-1841-11eb-9f46-18ed55a95b02.png)

但是页面显示的是这样的：
![image](https://user-images.githubusercontent.com/38599758/97250616-513fab00-1841-11eb-919b-e33b8b7369c9.png)

会把代码改写。

**Comment by 1205747671** [comment]
页面：http://qyb.cool/archives/springdatajpa%E4%BA%8C%E4%BD%BF%E7%94%A8springdatarepository

另外后台修改代码风格无效。

**Comment by 1205747671** [comment]
出现问题的代码：
```
public interface CrudRepository<T, ID> extends Repository<T, ID> {

  <S extends T> S save(S entity);      1

  Optional<T> findById(ID primaryKey); 2

  Iterable<T> findAll();               3

  long count();                        4

  void delete(T entity);               5

  boolean existsById(ID primaryKey);   6

  // … more functionality omitted.
}
```

 <S extends T> 会被改写

**Comment by xzhuz** [comment]
这个问题确实很奇怪，我晚上的时候看看。

**Comment by xzhuz** [comment]
你可以把你的整篇文章发给我看下吗？只是这块代码看不出来什么，且我这边还是正确渲染的

**Comment by 1205747671** [comment]
就是这段代码：
```
public interface CrudRepository<T, ID> extends Repository<T, ID> {

  <S extends T> S save(S entity);      1

  Optional<T> findById(ID primaryKey); 2

  Iterable<T> findAll();               3

  long count();                        4

  void delete(T entity);               5

  boolean existsById(ID primaryKey);   6

  // … more functionality omitted.
}
```

在后台的markdown是正确渲染的。
但是到了前端以后，其中的
```
 <S extends T> S save(S entity);      1
```
会变成
```
<s extends="" t=""> S save(S entity);      1
```
页面的标签会增加 ：
```
<s extends="" t="">
```
然后页面的所有内容都会添加上 s 标签

```
s {
    text-decoration: line-through;
}
```

**Comment by xzhuz** [comment]
> 就是这段代码：
> 
> ```
> 
> public interface CrudRepository<T, ID> extends Repository<T, ID> {
> 
> 
> 
>   <S extends T> S save(S entity);      1
> 
> 
> 
>   Optional<T> findById(ID primaryKey); 2
> 
> 
> 
>   Iterable<T> findAll();               3
> 
> 
> 
>   long count();                        4
> 
> 
> 
>   void delete(T entity);               5
> 
> 
> 
>   boolean existsById(ID primaryKey);   6
> 
> 
> 
>   // … more functionality omitted.
> 
> }
> 
> ```
> 
> 
> 
> 在后台的markdown是正确渲染的。
> 
> 但是到了前端以后，其中的
> 
> ```
> 
>  <S extends T> S save(S entity);      1
> 
> ```
> 
> 会变成
> 
> ```
> 
> <s extends="" t=""> S save(S entity);      1
> 
> ```
> 
> 页面的标签会增加 ：
> 
> ```
> 
> <s extends="" t="">
> 
> ```
> 
> 然后页面的所有内容都会添加上 s 标签
> 
> 
> 
> ```
> 
> s {
> 
>     text-decoration: line-through;
> 
> }
> 
> ```
这段代码我试了下，是好的。

**Comment by 1205747671** [comment]
嗯我重新更新了下halo-theme-xue_hotfix_2.zip，没问题了，可能是其他的某种问题。。？

但是代码风格问题更改无效需要再提issue么

**Comment by xzhuz** [comment]
> 但是代码风格问题更改无效需要再提issue么

可以，重新提一个吧
