### ISSUE TITLE
代码格式显示不正常，后台可以正常显示

### ISSUE THREAD

**Issue by sheiy** [xzhuz/halo-theme-xue#97]
https://sheiy.ownw.site/archives/spring%E8%AE%B0%E5%BD%95%E6%97%A5%E5%BF%97%E9%9D%9Eaop%E5%92%8Cfilter%E7%89%88

**Comment by xzhuz** [comment]
后台有开关是否开启代码高亮，你可以把这个开关打开
![image](https://user-images.githubusercontent.com/23736683/98220338-1b10d280-1f89-11eb-9b00-30703cf642d5.png)

**Comment by sheiy** [comment]
![image](https://user-images.githubusercontent.com/12210038/98319489-d5e9b080-201b-11eb-93df-905e104c82ed.png)
一样。。试过的

**Comment by sheiy** [comment]
![image](https://user-images.githubusercontent.com/12210038/98321078-27476f00-201f-11eb-980a-3e2b3a54e062.png)
这几行代码引起的问题，markdown插件的问题？

**Comment by xzhuz** [comment]
不是的，md是用的前端解析

**Comment by xzhuz** [comment]
暂时还不确定是什么问题，你试试1.2.2版本中的 halo-theme-xue_1.2.3_beta.5.zip 这个最新的安装包呢？

**Comment by sheiy** [comment]
@xzhuz halo-theme-xue_1.2.3_beta.5.zip 这个可以正常显示

**Comment by li1753846989** [comment]
halo-theme-xue_1.2.3_beta.5.zip  还是这样
![image](https://user-images.githubusercontent.com/50787560/100591976-7b4d2700-3331-11eb-9282-57c8c88dc3d0.png)

**Comment by li1753846989** [comment]
![image](https://user-images.githubusercontent.com/50787560/100592046-90c25100-3331-11eb-8464-febf033bf560.png)

**Comment by xzhuz** [comment]
请关注 https://github.com/xzhuz/halo-theme-xue/releases/tag/1.2.3.beta.6

**Comment by xzhuz** [comment]
请关注[1.2.3](https://github.com/xzhuz/halo-theme-xue/releases/tag/1.2.3)版本
